### ISSUE TITLE
Buzzier Bees' Apiarist houses absent [Mod compat]

### ISSUE THREAD

**Issue by MScott7** [TelepathicGrunt/RepurposedStructures#105]
With both Repurposed Structures and Abnormals Buzzier Bees present, Apiarist houses only seem to generate within vanilla villages (which seem to be very uncommon with R.S. installed). Would it be possible to allow Apiarist houses to generate within R.S. village variants as well?

**Comment by TelepathicGrunt** [comment]
Someone or me will have to make a new datapack to add the houses to all RS villages. It’s a bit of work but I can look into it much later. Basically, spawn the Buzzier bees house piece with a structure block, do the changes and save a new variant for each rs village (minus nether villages), shove the new nbt files into a datapack, and make new template pool file for each village in the datapack but within the pool_additions folder and that will inject the new pool entries to my village’s pool file.

**Comment by pm065** [comment]
I might give it a shot, along with an attempt to update the Environmental pack to add carpenter/ceramist houses :)
I have tried to update structures before with success but ended up getting bored with it (I was making bigger changes than swapping things around, haha) so I think I'll be able to do this

Edit: If you want you can unassign yourself and assign me to do it, since I don't have any mods to maintain I probably have a bit more time (:

Edit 2: Oh I found another thing for Environmental; update the Flower Forest Pyramid to have some Wisteria stuff on it like leaves and logs

Edit 3: So I have the basic skill level required to do this. Excellent. I won't edit this any further until I've done the Apiarist houses like the OP said :)
![2021-06-13_11 27 04](https://user-images.githubusercontent.com/81559564/121803650-8f57d680-cc3a-11eb-921c-0e26a456a535.png)

**Comment by pm065** [comment]
Oh, another thing for Environmental; update the Flower Forest Pyramid to have some Wisteria stuff on it like leaves and logs

**Comment by TelepathicGrunt** [comment]
Here's some instructions I left someone on how to make a datapack for RS. Might be helpful for you

-----

Download my rs_pieces world from here and enter it.  You can find all my village pieces in there.
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/releases/tag/0.0.10

 Go to a village house and change it to a building in the style of Environmental's Carpenters and Ceramicists with the right workstation. Put a villager in there too so it gets the profession. Leave the jigsaw block alone on the edge of the house bounding box. In the structure block, you can make the boundary bigger or smaller to fit the house. Change the name of the house on the end of the name field to "carpenter" or "ceramist". 
https://www.youtube.com/watch?v=umhuRXinD3o

Hit save and now go into the world's save folder and find the new generated folder in the rs_pieces world folder with the nbt file inside. Take that and put it into a new datapack. Now go to this datapack for ice and fire compat, take the repurposed structures folder and put it into your datapack and edit all the houses.json files for each village to point to your new nbt pieces.
https://github.com/TelepathicGrunt/RepurposedStructures/releases/tag/0.0.3

You can delete the decor files as you arent adding new decors. 

If it is setup right, my mod will look into all datapack's pool_additions folder, find the pool file (the houses.json), and inject all the houses it finds into my villages. That's what this newest update allows so you can make multiple datapacks that adds houses and they wont conflict with each other!

**Comment by pm065** [comment]
it works
![2021-06-15_21 15 12](https://user-images.githubusercontent.com/81559564/122117475-cdadeb00-ce1e-11eb-8b88-e1c862871904.jpg)
ugly base will be fixed, didn't really know what to do there

see this excellently named repositary: https://github.com/pm065/RepurposedRepurposedStructures/issues/1 for images of them all and some more information

**Comment by TelepathicGrunt** [comment]
Nice! For the base, you can replace those with structure void and it will not replace land anymore

**Comment by pm065** [comment]
I just committed a massive thing, fixing tons of issues. TelepathicGrunt and OP, I'll put up a zipped release, if you have time could one/both of you double-check it?
I'll just grab a quick demo of the slightly overhauled houses. The bases have mainly been replaced by void, except the bit underneath. The reason there was a base is that BB's original apiaries have one.

Edit: @TelepathicGrunt it's up and @MScott7 your wish has been granted, see
- https://github.com/pm065/RepurposedRepurposedStructures/releases 

:D

**Comment by pm065** [comment]
Okay then, no response yet... I might just get started making an Environmental expansion with carpenter/ceramist houses, willow swamp mineshafts and wisteria flower temples.

I also have a question: is it possible, in an environment with no mods modifying datapack behaviour (of which there are none that I know of), with **only datapacks**, to create an entirely new structure such as, for example, an Autumnity maple village in that mod's biomes? Would open up a lot of opportunities.

**Comment by TelepathicGrunt** [comment]
@pm065 sorry for late reply, it looks good but you should bump up the pool weights to 5 or 6 as it is pretty hard to find the houses imo and it would help they be able to spawn as they are larger (which means they have less valid spaces to spawn in). And when you upload the datapack, make sure you select the data, pack.mcmeta, and readme and send those into a zip file. If you zip BuzzierBees_, it becomes a zip file of a folder which cannot be dragged into minecraft and used right away without unzipping.

After that change, would you be alright if I link to your datapack on my mod page with credit to you of course?

As for the new structures with only datapacks, you would have to hijack the village structure by making a new configuredstructure, overwrite the entire biome json of the biome you want to add the structure to, and make sure that biome does not have any other village based structure as only one village-backed configuredstructure can spawn in a single biome. I would encourage usage of this mod instead which allows for you to create truly independent structures to biomes that you want without overwriting the biome json. https://www.curseforge.com/minecraft/mc-mods/shulkers-super-simple-structure-system


If you want to reach out to me and talk easier instead of GitHub, you can find my #telepathicgrunt-mods channel in MMD discord server here: https://discord.gg/SM7WBT6FGu I am TelepathicGrunt on there!

**Comment by pm065** [comment]
> @pm065 sorry for late reply, it looks good but you should bump up the pool weights to 5 or 6 as it is pretty hard to find the houses imo and it would help they be able to spawn as they are larger (which means they have less valid spaaaces to spawn in). And when you upload the datapack, make sure you select the data, pack.mcmeta, and readme and send those into a zip file. If you zip BuzzierBees_, it becomes a zip file of a folder which cannot be dragged into > minecraft and used right away without unzipping.

1. okay! I thought they were a little tricky to find, but I could hardly find any other special ones either, so I though those were meant to be rare. 

2. oops

> After that change, would you be alright if I link to your datapack on my mod page with credit to you of course?

Of course! It's no use if nobody can see it :smile:

> As for the new structures with only datapacks, you would have to hijack the village structure by making a new configuredstructure, overwrite the entire biome json of the biome you want to add the structure to, and make sure that biome does not have any other village based structure as only one village-backed configuredstructure can spawn in a single biome. I would encourage usage of this mod instead which allows for you to create truly independent structures to biomes that you want without overwriting the biome json. https://www.curseforge.com/minecraft/mc-mods/shulkers-super-simple-structure-system

That's a thing???? Thanks so much! A dependency is better than a (based on how you described it) hack, I guess.

> If you want to reach out to me and talk easier instead of GitHub, you can find my #telepathicgrunt-mods channel in MMD discord server here: https://discord.gg/SM7WBT6FGu I am TelepathicGrunt on there!

Really sorry, but I make a point to avoid Discord. My experiences of it have not been pleasant 🙃

Sorry if this comes out wrong on first post, github's UI seems to have broken after I installed a few firefox extensions so I can't check the preview. I'm trying to narrow down which one it is.

**Comment by pm065** [comment]
@TelepathicGrunt alright, it's up!

- https://github.com/pm065/RepurposedRepurposedStructures/releases/tag/BuzzierBees-v1.0
- https://github.com/pm065/RepurposedRepurposedStructures/releases/tag/BuzzierBees-Environmental-v1.0

 Gonna make a curse page for the datapacks as well, as a bulk download for both + every structure datapack I make beyond these.
Edit: Alright, the file is pending moderation!
Edit2: It's up on Curse! https://www.curseforge.com/minecraft/customization/re-re-struc

**Comment by TelepathicGrunt** [comment]
Closing this thread now as I listed your buzzier bees pack on repurposed structure's modpage now!  @MScott7 you can use that datapack to add buzzier bee's houses to my villages!

**Comment by pm065** [comment]
Sorry for continually harassing you, but one last tiny thing: it might be an idea to simply link [here](https://github.com/pm065/RepurposedRepurposedStructures/wiki), since I may be updating these quite frequently (I want to make ReStruc compatible with every mod in my modpacks). Rather than pester you every time I make a change, I'll just update the wiki.

**Comment by TelepathicGrunt** [comment]
Sounds good!
