### ISSUE TITLE
Server Crash with World Gen with Terraforged

### ISSUE THREAD

**Issue by judicius** [TelepathicGrunt/RepurposedStructures#111]
MC 1.16.5
TerraForged 0.2.11
Repurposed Structures 2.7.5
Forge 36.1.32

Crashreport: https://gist.github.com/judicius/cd491226f05f3d845eeda652c17cbbb2
Debug: https://gist.github.com/judicius/44667ab18270cb06ae8f5d8ad9efe27a

Terraforged Preset: https://gist.github.com/judicius/1a7b58d6f5a1dcc1dcf101988054e2e5

Crossreference: https://github.com/TerraForged/tracker/issues/132

**Comment by TelepathicGrunt** [comment]
This is not a Terraforged issue. This is most likely, one again, a mod breaking tags and thus, wrecking a lot of worldgen mods. This seems to be becoming more common hmm.

Do you have VanillaFoodPantry mod on? If not, can you put on the mod called [Blame](https://www.curseforge.com/minecraft/mc-mods/blame), get the crash to happen again, and then share the latest.log file?

It will help me out a ton as Blame may find the problematic mod classloading TagCollectionManager too early.

**Comment by judicius** [comment]
I'll install Blame on the server and if it happens again update the ticket. Unfortunately I can't easily duplicate as I had to delete player data to reset positioning in order to be able to join the server.

**Comment by judicius** [comment]
Heres a fresh boot debug log with Blame installed. Seems Repurposed Structures and Caves and Cliffs Backport may be having issues.

https://gist.github.com/judicius/1a2e5d39a23806f66f13090d4a47555b

**Comment by TelepathicGrunt** [comment]
Oh it looks like it is terraforged. It must be new for them to add their tag fix code as I never seen this from them before. But as a result of classloading that TagCollectionManager too early before The Undergarden could bind their tag in code, the Undergarden's undergarden:lake_virulent configuredfeature blows up because The Undergarden's tag is no longer in the Tag manager. And this error in their worldgen configuredfeature cascades and break a ton of other mod's stuff as well including my mod. Terraforged needs to either remove their Tag Fix code or move it till way after mod init is done (after FLMCommonSetupEvent should be ok). Hopefully this is enough info for them to fix it

![image](https://user-images.githubusercontent.com/40846040/123522241-1caf1800-d68a-11eb-9821-454f73ca58e0.png)

**Comment by judicius** [comment]
Looks like they pushed 0.2.12 out 46 minutes ago with a fix

Changes:

    - Fixes load-order compatability issue with undergarden (problem introduced in 0.2.11)
