### ISSUE TITLE
Mod Loot Table Importing not working properly with Dungeons Gear

### ISSUE THREAD

**Issue by AmphyEX** [TelepathicGrunt/RepurposedStructures#121]
Prior to version 3.0 and the introduction of the new config system, items from Dungeons Gear would consistently spawn in Repurposed Structures Loot Tables. After 3.0, Dungeons Gear items no longer spawn in any Repurposed Structures loot tables regardless if Mod Item importing is true or false. Is this a bug with Mod Item importing feature?

Edit: I did testing with other versions of both mods and found that Dungeons Gear items spawned in none of the repurposed structure versions. I am unsure if this is a configuration problem on my end or if this is a bug in this mod's loot table importing.

**Comment by TelepathicGrunt** [comment]
oh it seems they added code that now hard checks the block's loot table and thus, bypasses me trying to roll vanilla's loot table. This is bad.
![image](https://user-images.githubusercontent.com/40846040/127770212-53d2a55e-d5dc-4193-847e-4309ac8476a2.png)

I'm surprised RS worked before because it shouldn't had with that code. Did you update Dungeon Gears at the same time? 

I'll contact the author to ask them to grab the loot table from the `LootContext context` instead.

**Comment by TelepathicGrunt** [comment]
This incompat was fixed in dungeons gear v3.0.21 update! closing now
