### ISSUE TITLE
Map in End Pyramid took too long to find an End Stronghold

### ISSUE THREAD

**Issue by Slaini** [TelepathicGrunt/RepurposedStructures#136]
Server crashes/times out when interacting with a trapped chest in an obsidian pyramid in the end.

[crash-2021-08-19_01.34.57-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures/files/7012125/crash-2021-08-19_01.34.57-server.txt)

**Comment by TelepathicGrunt** [comment]
It’s not a crash. Your server watchdog killed the server after an explorer map in the pyramid took too long to find an end stronghold but I do not know why. It should not take a full 60 seconds as in my testing, it tends to be about 7 seconds with the /locate command. 

Did you make the End Stronghold super rare? What coordinate was the End Pyramid at? Can you provide a multimc or curseforge launcher mod profile export so I can download the mods instantly to test? (Though I can download the mods individually but it’ll take time)

**Comment by Slaini** [comment]
I didn't edit the rarity of any structures
This is the modpack : https://www.curseforge.com/minecraft/modpacks/anduins-wrath
This is the seed idk if that would help : -3276858781065923903
and the coordinates are : 2311 64 -1984
and when i do /locate repurposed_structures:stronghold_end it's pretty much instant and and the structure is 9415 blocks away.

Hope that will help.

**Comment by TelepathicGrunt** [comment]
Hmm. Perhaps it is because I set the map to skip existing chunks to find fresh end strongholds. But if the eyes of ender loads the chunk or the server pregens, in theory, that would make the map have to search crazy far. 

If you’re alright with doing a test, I have an idea we can do to see if that’s the case. 

Download the 1.16.5 lucky banners loot table datapack here. This is the default loot tables in RS right now:  https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/releases/tag/0.0.11

Unzip the file and edit the end pyramid’s two loot tables to change this line from true to false. 
https://github.com/TelepathicGrunt/RepurposedStructures/blob/d1b166fd8af8f8ade6ce6d2fcb45857fbcbe787c/src/main/resources/data/repurposed_structures/loot_tables/chests/pyramid/end_chest.json#L255

Put the datapack on the server and open one of the chests in the end pyramid and see if it can create the map safely for your server. If it does, I’ll edit all my loot tables to not skip existing chunks and always return closest structure it is looking for

**Comment by TelepathicGrunt** [comment]
Actually, it seems to be the map zoom. Finding the stronghold is fast. But the map needs to generate the chunks to do the map preview. At zoom 4, with the end being slow to generate (even slower with lots of end mods on), it seems to take a while. i'll cut the zoom for the maps in the End down to 1 to massively speed up explorer map generation in chests. (You can do this change by editing the loot table datapack if you dont want to wait for next RS update)

**Comment by TelepathicGrunt** [comment]
should be fixed in newest update!
