### ISSUE TITLE
[Suggestion] Swamp Expansion Compatibility - Swamp villages use willow instead of oak

### ISSUE THREAD

**Issue by Darkiceflame** [TelepathicGrunt/RepurposedStructures#14]
With the addition of village variants, it would be neat if swamp villages had the option to use willow wood from the Swamp Expansion mod when that mod is installed, instead of oak.

**Comment by TelepathicGrunt** [comment]
Since the village pieces are nbt files, it’s more up to the user to replace these village pieces through data packs as jigsaw structures generates from nbt instead of code. 

However, if you give me a day or so, I could try using my python script to replace the oak/spruce wood with willow wood in the nbt files and give you the data pack to override the default swamp village. :)

**Comment by Darkiceflame** [comment]
That would be lovely!

**Comment by TelepathicGrunt** [comment]
Thank you for asking about this as I am working on the datapack, I just found out my mod isn't loading it correctly it'll be fixed in v1.7.2 update! Hopefully now it'll be stable until 1.16 release lol

Anyway, here's the datapack! Download it, go into your world's save folder, and put the folder into the datapack folder. Now when you load the game with Swamp Expansion and Repurposed Structures, the swamp villages will use their wood and blocks! I hope it looks good! (I kept the fences as Spruce Fences as Willow Fence looked weird)
[Repurposed_Structures-Swamp_Expansion.zip](https://github.com/TelepathicGrunt/RepurposedStructures/files/4807148/Repurposed_Structures-Swamp_Expansion.zip)


Just re-open this issue if the pack doesn't work or the village isn't what you were looking for :)
