### ISSUE TITLE
Survive causes crash with Origins. (not RS issue)

### ISSUE THREAD

**Issue by SHXRKIEgg** [TelepathicGrunt/RepurposedStructures#147]
Everytime without fail the game freezes at creating the world after 2nd attempt and creates a crash log.
The reason I say second attempt is cause everytime I reinstall the Better MC or Medieval MC Modpack and update the mods, it works the first time and after that it always freezes. Not sure if this has to do with RS since its the only thing that shows in the log but I know its Caves and Cliffs as I tested all the new Updates and that was the culprit.

https://pastebin.com/AwVePkfd

**Comment by TelepathicGrunt** [comment]
![image](https://user-images.githubusercontent.com/40846040/137568045-a9cec4c4-7c0e-448d-8437-5672cc7d15a6.png)
You're modpacks are using [old outdated versions of the datapacks](https://github.com/TelepathicGrunt/RepurposedStructures/issues/126) that are known to cause issues. (the ones made by pm097) I would say to delete the `RRS_EnvironmentallyFriendly.zip`, `RRS-BuzzierVillages.zip`, `RRS-RepurposedDelight.zip`, and `RS_Abnormals__Farmers_Delight_Compat_Fixed.zip` and download the fixed datapacks from here: https://github.com/TelepathicGrunt/RepurposedStructures/releases

The datapacks that replaces those are:
https://github.com/TelepathicGrunt/RepurposedStructures/releases/tag/0.0.5
https://github.com/TelepathicGrunt/RepurposedStructures/releases/tag/0.0.4
https://github.com/TelepathicGrunt/RepurposedStructures/releases/tag/0.0.1

I have a feeling that if you did update RS, the latest.log file would've showed that one of the datapack's processors blew up just before the stacktrace error. The reason I say this is because the latest version of RS has a check for that specific crash to give more info because someone else reported this before when I broke the Farmer's Delight pack originally when I split up pm097's datapacks that were also crashing. Now they shouldn't cause any issues unless the compat mods adds or removes blockstate properties from their blocks that are used within those datapacks. 

try that and let me know if that resolves the issue for you

**Comment by SHXRKIEgg** [comment]
I have already replaced them with the new ones as im working on a new update and the issue still persists. Here is a screenshots of the datapacks. These are also fresh downloads just incase.
![image](https://user-images.githubusercontent.com/79353591/137571500-6d0027fa-0fc9-4b7c-81e3-79764af9392c.png)
Here is another Crash Report.
https://pastebin.com/shWmX5aV

**Comment by TelepathicGrunt** [comment]
Please send me the latest.log file from the logs folder. Not the crash report. The crash report omits a ton of important info that could help pin down the issue

**Comment by SHXRKIEgg** [comment]
File oto big for pastebin
Download: [latest.log](https://github.com/TelepathicGrunt/RepurposedStructures/files/7356660/latest.log)

[14:20:26] [Server thread/ERROR]: 
 Repurposed Structures: Crash is about to occur because an entry in a datapack does not exist in a registry or failed to resolve an entry.
 Entry failed to be resolved: ResourceKey[minecraft:root / minecraft:worldgen/configured_feature]
 Registry being used: "repurposed_structures:cobblestone_patch"

**Comment by SHXRKIEgg** [comment]
So the problem lies with the Repurposed_Structures-Ice_and_Fire Datapack. I tested all the datapacks and that one is causing the crash/freeze

**Comment by TelepathicGrunt** [comment]
Interesting. Yeah remove that datapack for now. I'll look into this and see what exactly is the issue and why. What is weird is "repurposed_structures:cobblestone_patch" should exist in the registry as I created and registered it.

**Comment by TelepathicGrunt** [comment]
Wait a second, i'm looking through the mod list for Better Minecraft modpack and I dont see ice and fire. Did you kept on the ice and fire datapack while also removing ice and fire? Because that will break the game lol

**Comment by SHXRKIEgg** [comment]
I should have it installed but I tested to make sure and its their and ran it again to make sure and still the same issue

**Comment by TelepathicGrunt** [comment]
Sorry for delay. Had family stuff to deal with. Anyway, I downloaded Better Minecraft with GDLauncher, selected all mods, updated them all, added Ice and Fire mod and the Repurposed Structures Ice and Fire compat datapack, create a world, and was able to find the buildings spawning in villages. No crashes or issue making worlds.
![image](https://user-images.githubusercontent.com/40846040/137649616-ec15e836-a117-4def-ac2d-a70a40eda1d5.png)

Are you positive that there's nothing else you did in your tests? Perhaps, could you send me the exact modpack instance that is causing the issue? I tested twice with these two datapack combinations and no issue each time:
![image](https://user-images.githubusercontent.com/40846040/137649712-2a82feec-f67b-4c7e-b5d8-7c37b7ef336e.png)

![image](https://user-images.githubusercontent.com/40846040/137649744-d322770a-e929-4ef0-9d56-8de5af295f3e.png)

**Comment by SHXRKIEgg** [comment]
Its the Medieval Minecraft Modpack I was testing not the main Better MC FORGE one that doesnt have ice and fire. Install the latest version of Medieval Minecraft and add the datapack

**Comment by TelepathicGrunt** [comment]
Thank you for clarifying. I was able to reproduce the issue with that modpack and updating it. After spending a few hours frustratingly trying mods, I looked closer at my latest.log file and it actually says the issue. Nothing about RS. This is what I see: https://paste.ee/p/YrvR8

The issue is the Survive mod has a survive:generic.heat_resistance file for Origins in it. However, this file is broken and causes Origin to throw a datapack parsing error that prevents players from entering the world. Upon disabling Origins, I was able to enter the world. I'm not sure who defined brute:piglin_neutrality and moth:glowaffinity as those two are also going to break Origins. If you can find all the mods that those 3 origins files are in and disable them, your modpack should work again. Then be sure to let those mods know so they can fix their files and register the stuff or whatever. I never used Origins myself so idk what that entails lol.

This took me way too long to figure out.
