### ISSUE TITLE
Server crash when i'm entering to the end

### ISSUE THREAD

**Issue by SzymZEROn** [TelepathicGrunt/RepurposedStructures#149]
If any person enters The End then the server crashes.

Console logs: https://bin.birdflop.com/uriyokaror.swift

Crash report: https://bin.birdflop.com/exurilekiw.p

https://user-images.githubusercontent.com/92884664/138148487-e8f65d3b-fe51-4d26-898e-171938b0b23d.mp4

**Comment by TelepathicGrunt** [comment]
Just looked at the log and it looked extremely familiar. And then i realized, you're using 3.1.0 RS which is outdated. This serverside crash was fixed in v3.1.3. But you should update straight to v3.3.1 so you get all the updates and some new structures too. 

Sorry about that. I should've realized this when you mentioned v3.1.0 back on curseforge. But yeah, update and the crash should go away. :)
