### ISSUE TITLE
Group configs

### ISSUE THREAD

**Issue by EternalOne11** [TelepathicGrunt/RepurposedStructures#155]
Could you add a group config for each structure type. This would make disabling entire groups far easier in the config. (such as a yes or no to all igloos for example.

**Comment by TelepathicGrunt** [comment]
I leaning on not doing that because my config is already very large and that would be extra work on my end. The configs for the structures are already grouped in the same files so it’s just like 3-4 extra seconds to copy/paste the turn off values into all the dungeons and stuff. Not sure if the actual benefit for users is worth the extra effort.

It may also confuse users thinking there’s no way to turn off one kind of dungeon because the config you mentioned primes them into thinking only a true/false can disable structures and there’s no per structure true/false. The big reason I baked the disabling of single structures into the spawnrates Config was to minimize the amount of Config entries so the Config file isn’t bloated ridiculously massive. (I’ll still need to reduce amount of redundant comments tho)

**Comment by TelepathicGrunt** [comment]
After thinking about it even more just to make sure I didn’t miss anything, yeah I don’t think this is worth the effort.

It would confuse other users to start looking for true/false entries for individual structures and that would be way too much work for me to add now (and would bloat the configs to about double their size).

The other thing is after really thinking about who disables all structures, that’s generally done as a one time thing and never turned back on. So the user spends a bit extra time to turn off all the structures and that’s really it. They don’t ever really reactivate all the structures ever again cause they disliked them enough to turn them all off. But if in the off chance, they do want to reactivate all the structures, all they have to do is move the config file someplace else and forge will regenerate the config with the default values. And then they can copy back in the modified config to turn off all the structures if they wish. 

So the extra time saved by me going the extra effort to make that config entry and the potential confusion is not really worth the effort when after turning off all the structures once, the user can just turn them all off and on again by moving config files easily.

Thank you though for the suggestion! It was good for me to think about this. But yeah the one thing I’ll definitely try and do is shrink the comments in the config files as much as I can so they take a lot less scrolling and thus, a bit easier to change the entries

**Comment by TelepathicGrunt** [comment]
Oh yeah forgot to mentioned here, as of 3.4.3 RS, the configs were significantly cleaned up so editing them should be much more of a breeze. So yeah thank you for getting me to look at the configs again lol

I don’t have internet for my laptop where I am but this is what the config looks like now. The comments were condensed into a single comment out at the top of each category so every entry is side by side
![Uploading D811B388-1977-4E31-ADE9-3FD88375C51B.jpeg…]()
