### ISSUE TITLE
Crash when using an old version of Waystones. (update to latest to fix)

### ISSUE THREAD

**Issue by Apiterbakar** [TelepathicGrunt/RepurposedStructures#156]
[crash-2021-11-20_20.03.58-client.txt](https://github.com/TelepathicGrunt/RepurposedStructures/files/7574595/crash-2021-11-20_20.03.58-client.txt)

**Comment by TelepathicGrunt** [comment]
It’s crashing here but that shouldn’t be possible as nothing should be null. https://github.com/TelepathicGrunt/RepurposedStructures/blob/bab45d77b7664e1b88c51431913a67e47ccd4e01/src/main/java/com/telepathicgrunt/repurposedstructures/utils/BiomeSelection.java#L74

To be clear, is this crash on your computer or on a server? If on a server, are you using mohist? And can you please send me a export of all the mods you are using or zipped up folder of mods? That way I can quickly autodownload and put on all the mods instead of spending a lot of time hunting down each one.

**Comment by Apiterbakar** [comment]
no its not on a server

**Comment by Apiterbakar** [comment]
and idk how to sned the zip file because i can't send it here

**Comment by TelepathicGrunt** [comment]
You can use Dropbox or Google drive if it is too large. But I guess I’ll just bite the bullet and take the time to search and download every mod manually.

**Comment by TelepathicGrunt** [comment]
I put on all the mods you had and I did not get any crash. I'm not sure what the best way to troubleshoot from here is. Though, you can try this test version of repurposed structures. It wont stop the crash but should print more info to help say what exactly is null. maybe that will help us
[repurposed_structures_forge-3.4.5b+1.16.5.zip](https://github.com/TelepathicGrunt/RepurposedStructures/files/7574861/repurposed_structures_forge-3.4.5b%2B1.16.5.zip)

**Comment by jasontamez** [comment]
I'm getting the same crash. It happens when I click "Single Player" -> "Create New World". I used the version above to get you a better error message.

`java.lang.RuntimeException: reverse tag of MINESHAFT is null`

    The game crashed whilst mouseclicked event handler
    Error: java.lang.NullPointerException: mouseClicked event handler
    Exit Code: -1

[crash-2021-11-23_15.29.26-client.txt](https://github.com/TelepathicGrunt/RepurposedStructures/files/7591128/crash-2021-11-23_15.29.26-client.txt)

[Mods (Drive link)](https://drive.google.com/drive/folders/1-G6y6Zp895whmTDZwesL791GHfV8_2Jw?usp=sharing)

**Comment by TelepathicGrunt** [comment]
Thank you @jasontamez, So it is saying that the reverse tag system is empty when that should literally be impossible unless another mod is somehow making Forge skip the FMLCommonSetupEvent which is... extremely bad.
https://github.com/TelepathicGrunt/RepurposedStructures/blob/bab45d77b7664e1b88c51431913a67e47ccd4e01/src/main/java/com/telepathicgrunt/repurposedstructures/RepurposedStructures.java#L162

After testing, the issue is that both you and @Apiterbakar are using a too old version of Waystone that seems like it is nuking my tag map somehow. Maybe causing an issue with FMLCommonSetupEven and keeping it from firing? Anyway, I was originally testing with the latest Waystones version which is why I could not reproduce the issue. 

Please update Waystones and lmk if that resolves your issues!

**Comment by jasontamez** [comment]
That did the trick. Working well now. Thanks!
