### ISSUE TITLE
(WAILA is the issue) Crash when looking at furnace in mushroom igloos

### ISSUE THREAD

**Issue by rsaihe** [TelepathicGrunt/RepurposedStructures#181]
When looking at the furnace in a mushroom igloo, the game instantly crashes. My crash log can be found [here](https://paste.sr.ht/~rsaihe/c8d27573d0120cf986d9b3ec8faf00a7d9ec0e32).

**Comment by TelepathicGrunt** [comment]
I'm gonna guess this more of an issue with waila or something. `mcp.mobius.waila.network.RequestTilePacket`

The furnace is literally just an empty normal furnace lol. Nothing special about it. 

You'll have to share that log with waila and let them know they need to fix their packet code. I can't find waila myself when i search online due to all the derivatives and the 1.11 version taking up results lol.

![image](https://user-images.githubusercontent.com/40846040/150255471-900423e2-f34a-424c-9feb-6f14cf7a6f7f.png)
![image](https://user-images.githubusercontent.com/40846040/150255503-eaea901e-0c4c-4cf1-88a2-14087bb2fe7c.png)

**Comment by rsaihe** [comment]
Ah, looks like someone already made an issue: https://github.com/Snownee/Jade/issues/88

Thanks for the help!

**Comment by TelepathicGrunt** [comment]
and they just closed that report with a fix lol. I guess I'll close mine now. Have a great day!

**Comment by rsaihe** [comment]
You too!
