### ISSUE TITLE
Underground bastions generate with too many entities and floating lichen

### ISSUE THREAD

**Issue by LeoBeliik** [TelepathicGrunt/RepurposedStructures#185]
**Describe the bug**
Underground bastions generate with a ton of skeletons on them, making the world lag a lot.
Also they spawn with floating lichen

**Version Info:**
 - Minecraft version: 1.18.1
 - Forge version 39.0.79
 - RS 4.2.11+1.18.1

**Screenshots**
![2022-02-23_10 08 41](https://user-images.githubusercontent.com/11804768/155326277-90dd8128-66b0-4705-b249-f155a50f62e4.png)

**Comment by TelepathicGrunt** [comment]
Copying an pasting my message from discord so that the response is documented and others can see this and can chime in if skeletons are an issue:

 the amount of skeletons in underground bastions is the same as piglins iirc. Or close to it. (Actually maybe I did increase the amount to make up for skeletons being weaker) Though I do not lag from the skeletons or notice any performance issues. Are you positive that the lag is actually from the skeletons or perhaps another mod is making entities take longer to tick? (Either way, doesn’t seem like an rs issue). 

If you want to really reduce skeleton amount, increase the weight of the empty pool element in these pool files by datapack https://github.com/TelepathicGrunt/RepurposedStructures/tree/latest-released/src/main/resources/data/repurposed_structures/worldgen/template_pool/bastions/underground/mobs

Also, the lichen isn’t rs. The rs bastions do not have lichen and spawn using the vanilla nbt piece placing so if another mod is placing lichen on edges of chunks, they are always going to cause floating lichen with all structures because structure pieces’s blocks are only placed within chunks. Thus if a mod places lichen on a chunk edge attached to the wall of the side chunk that hasn’t spawn it’s structure yet, that lichen will be floating if the other chunk generates and replaces that wall with air

**Comment by TelepathicGrunt** [comment]
![BFF5EF70-F80D-4EEF-B2C4-6DE452DF0671](https://user-images.githubusercontent.com/40846040/155330687-d238783b-051f-4d79-a45a-462595585dd3.png)

more documentation purposes. Underground bastion spawns 50-70 skeletons so it seems unlikely that Skelton lag is coming from the structure itself. Most likely is another mod spawning extra mobs around so I’ll close this. 

Lmk if you figure out what mod is duplicating spawns or whatever so I know what to ask people if they report the same issue later.
