### ISSUE TITLE
1.18.2 version not generating structures

### ISSUE THREAD

**Issue by explicitargo** [TelepathicGrunt/RepurposedStructures#189]
I got the 5.0.1 RS version on 1.18.2 Forge 40.0.12 and have used the /locatebiome command to try and find the structures. They do appear on the autocomplete (#repurporsed_structures etc) but when I tp and search nearby I dont see anything. 

I had other mods but now I'm trying to run it with just RS alone and the problem persists.

**Comment by TelepathicGrunt** [comment]
testing the 1.18.2 version from curseforge, I am able to locate and find RS structures. Use /locate command. not /locatebiome btw. /locatebiome is for finding biomes. Not structures. The #repurposed_structures tag that shows up in /locatebiomes is only for my structures to use and know what biomes they can spawn in. That's why you need to use /locate to find the actual structures themselves.
![image](https://user-images.githubusercontent.com/40846040/157767096-fe776744-cc81-45b7-a13b-504c51eb59d9.png)
