### ISSUE TITLE
structure generated in the middle of a village in a pvj biome

### ISSUE THREAD

**Issue by ekiplier** [TelepathicGrunt/RepurposedStructures#190]
![Untitled](https://user-images.githubusercontent.com/74121461/157910747-b504285b-4e8e-4780-b729-fd2509d5488b.png)

This temple spawned in the middle of a village, interrupting one of the village buildings, in a project: vibrant journeys biome. 

[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures/files/8233790/latest.log)

**Comment by TelepathicGrunt** [comment]
This is intentional and fine. Vanilla desert pyramids can spawn inside desert villages. So I did not add any checks to keep my pyramids from my villages. The main stay-away-from-other-structures check in repurposed structures is RS Outposts cannot be near any RS Village and can’t be near an Overworld City either. 

Vanilla example:
![9BB36D4A-448D-45F4-9697-75D8FF75ADD9](https://user-images.githubusercontent.com/40846040/157912537-fd182b89-aac2-4c82-9023-5042e9018105.jpeg)
