### ISSUE TITLE
[1.16.2] Crash whilst generating the world. (In a WIP Modpack.)

### ISSUE THREAD

**Issue by Gbergz** [TelepathicGrunt/RepurposedStructures#21]
Title^

Crash is happening when the world is in the process of being created.

**Minecraft Version:** 1.16.2
**Forge Version:** 33.0.23
**Mod Version:** [2.1.1](https://www.curseforge.com/minecraft/mc-mods/repurposed-structures/files/3046635)

**Modlist:** https://gist.github.com/Gbergz/916fd738f58b6bff3b97c08f4e405760
**Crash-Report:** https://hastebin.com/imipikokil.pl

**-** Gbergz

**Comment by TelepathicGrunt** [comment]
Just wondering, was this on a server or single player?

**Comment by TelepathicGrunt** [comment]
Nvm I see it has integrated server so it's single player. Hmm. I wonder what's going on to cause this crash...

**Comment by TelepathicGrunt** [comment]
Ok I see the issue. Someone is making a DimensionStructuresSettings class for their dimension but in their `Map<Structure<?>, StructureSeparationSettings> structures;` field, they are setting an immutable map which is bad. Especially as I need to put my structures into that field or else, my structures will spawn in every single chunk with no spacing. 

This sounds like a bug report for another mod but first, I need to know which mod it is lol. Which mods do you have that adds a new dimension?

I'll apply a fix on my end to prevent the crash but I can't fix the spacing issue until they use a normal map instead of an immutable map. I'll try and add something too that will write to the logs of which mod's dimension is using an immutable map. Give me a moment or two!

**Comment by TelepathicGrunt** [comment]
Here, can you put on this jar and test the game with it? After you enter a world, exit the game and give me the latest.log file in the logs folder below the mods folder. That should say which mod needs to remove the immutable map in their dimension. I'll make that bug report to them once I know which mod it is but otherwise, the game should work fine except for when generating structures in that buggy dimension.

[repurposed_structures-1.16.2-2.1.2b.zip](https://github.com/TelepathicGrunt/RepurposedStructures/files/5152777/repurposed_structures-1.16.2-2.1.2b.zip)

**Comment by Gbergz** [comment]
Alright here you go the latest.log below:
[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures/files/5153221/latest.log)

**Comment by TelepathicGrunt** [comment]
Yeah it appears to be The Mining Dimension causing this. I'll talk to them to see if they fix that map. And I'll also see about fixing the patch to not spam the logs so much on the next release. Thank you for reporting this! :)

**Comment by TelepathicGrunt** [comment]
Scratch that, this is 100% an error on my end. It seems when anyone makes a datapack or json chunkgenerator, it make an immutable map which crash my mod Or at least, that's what I think is happening. Shoot I'll need to make another fix.

**Comment by TelepathicGrunt** [comment]
v2.1.2 is now approved and should fix this issue. :)
https://www.curseforge.com/minecraft/mc-mods/repurposed-structures/files/3047392
