### ISSUE TITLE
Problem with Quark's Variant Chests config option for Repurposed Structures' structures only.

### ISSUE THREAD

**Issue by DarthCaesium** [TelepathicGrunt/RepurposedStructures#210]
Long story short, it was working before, but with newer versions of Repurposed Structures, the variant chests don't seem to work, but they do work for other modded structures. I have gone to the effort of even modifying Quark's config to replace chests in every one of my mods' structures, and the only mod that this has refused to work with is Repurposed Structures. Could you please take a look at this? Could there be some problem with the way in which the structures are coded that prevents this?

**Comment by TelepathicGrunt** [comment]
This is a known issue where quark seems to have a bug. Issue report has been made to them here:

https://github.com/VazkiiMods/Quark/issues/3704

**Comment by TelepathicGrunt** [comment]
RS’s structures are using a modified jigsaw system with vanilla’s json structure system. The chests in rs’s structures are saved to the structure nbt file just like any other normal structure. As far as I can tell, there’s nothing unique or special about my chests. They are fairly standard.

**Comment by DarthCaesium** [comment]
In which version of Quark is the bug not present in?

**Comment by TelepathicGrunt** [comment]
All quark versions on 1.18.2. I looked closer at the code they run. 
![image](https://user-images.githubusercontent.com/40846040/172028807-d9b6c47a-2a47-4ef9-bc9b-592c3d4cd68e.png)

Quark is trying to get the registry name of the base structure. Not the Configured Structure Feature like they should be doing. The reason why this is bad is because "repurposed_structures:generic_jigsaw_structure" is used as the base structure to create each individual configured structure feature that you see when you do the /locate command. Currently, If you put "repurposed_structures:generic_jigsaw_structure" into quark's config, it'll replace like 70% of all my structure's chests.

Quark will need to update to fix this

**Comment by TelepathicGrunt** [comment]
It looks like they fixed it now with Quark-3.2-358.jar. I'm gonna give it a try in a few minutes

https://www.curseforge.com/minecraft/mc-mods/quark/files/3840125

**Comment by TelepathicGrunt** [comment]
yep fixed. Closing now
