### ISSUE TITLE
Crash with processor lists when reusing 1.18.1 or older world in 1.18.2 or newer

### ISSUE THREAD

**Issue by LaBestiaBrutal** [TelepathicGrunt/RepurposedStructures#220]
Hi, good day sir! I have been using you mod in my server for several months, it happens when everything is loaded and somehow it gives me an error in the console at the end of the process, then when I log in and try to move to generate new terrain it just freezes; there is no crash rep but I leave you a log. I am not sure if this mod is responsible, but it says something about jigsaw witch huts for Repurposed Structures, maybe you can help. Thanks!

https://gist.github.com/LaBestiaBrutal/c38d9d6049753b757b66715e75080bc9

**Comment by TelepathicGrunt** [comment]
You updated a world from like 1.18.1 Mc or older to 1.18.2 I’m betting. No, I’m sure lol. 

Updating modpacks across Mc version is always bound for issues.

In this case, I did a refactor to clean up some stuff in my mod in 1.18.2. Part of this was renaming and moving processor lists which is used for randomizing blocks in structures.

The issue is the old 1.18.1 or older chunks that were in the process of being generated are attempted to be resumed generation in 1.18.2. And in doing so, they see the old structure data, try to load it, reach a line referencing a processor list that no longer exist, and then crashes because the processor list is gone. This is a vanilla bug if anything and affects any mod or datapack refactoring their processor lists while keeping the structure name the same.

Use this datapack which returned the old processors again as dummy processors so the game can load the old chunks without crashing
https://github.com/TelepathicGrunt/RepurposedStructures-Quilt/issues/199#issuecomment-1132217839

**Comment by LaBestiaBrutal** [comment]
Thanks!! I appreciate it, really. I was planning to add just a few mods to my modpack, but the folder got bigger and bigger and then problems like these with it xD but the fun is too much, so...
It is not giving me the error anymore, but going to keep generating new terrain to see if there are more mods involved.
