### ISSUE TITLE
Generation Issues with other mods (Quark)

### ISSUE THREAD

**Issue by xhatz** [TelepathicGrunt/RepurposedStructures#223]
Hello! Basically, when using other mods that change the carver or generate new caves, weird things can happen. Here is an example: 
![image](https://user-images.githubusercontent.com/1364915/180801336-44b50cd8-20a6-4942-a8a8-d74d529f6a66.png)
Is there any known fix for this please?

**Comment by TelepathicGrunt** [comment]
There is not. This is caused by quark using a feature to make its caves instead of a carver. So what this means is in one chunk, quark carves out the cave for that chunk. Then in the next chunk over, the ocean mineshaft starts generation, sees it borders air in the side chunk, places prismarine in the side chunk to try and enclose itself from air, and then quark’s cave carver eats away at the mineshaft in the current chunk, leaving only the prismarine wall in side chunk. 

The solution would be to stop trying to make caves in the feature stage. It won’t work and will always have edge cases and issues with other features or structures that are larger than a chunk and replaced air. The best solution is to do the cave carving in the carver stage as a carver because then the change is applied to all chunks before any feature or structure is ran and so the feature and structure gets the true carved area properly.

there isn’t anything I can do on my end other than just disabling my structures entirely.

**Comment by TelepathicGrunt** [comment]
Also, I thought quark got rid of their cave feature entirely in 1.19. If you’re using an older version of Mc, do note I won’t be backporting updates anymore for older Mc versions of my mod. If this issue is occurring in 1.19 and I have some examples of mods still using features to make caves, lmk and I’ll try and talk to those modders on alternatives to accomplish their goal.

**Comment by xhatz** [comment]
Thank you for the detailed explanation! And my bad I should've had mentioned it was on 1.16 haha, sorry. I'll just disable Quark's cave modifications.
