### ISSUE TITLE
Crash in modpack about loot table

### ISSUE THREAD

**Issue by NOS73** [TelepathicGrunt/RepurposedStructures#224]
I'm now hosting a modded server with a modpack containing RepurposedStructures. My server suddenly crashes without any notice. I tried to restart the server but my console returned serval lines about cannot load loot table. I know nothing about Java coding and I tried to fix this by replacing all the config files of this mod. Unfortunately, it doesn't work. This is the crash report from my server.
[crash-2022-08-05_23.51.07-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures/files/9274055/crash-2022-08-05_23.51.07-server.txt)

**Comment by TelepathicGrunt** [comment]
That crash has nothing to do with repurposed structures or loot tables. This is the line I am looking at

net/mcreator/ecofriendly/client/particle/OilDripParticleYMParticle for invalid dist DEDICATED_SERVER

The Mcreator mod Ecofriendly is crashing because they try to load a clientside only class while on the server which is not allowed. They will need to fix that. You can remove Ecofriendly to stop the crash and let them know about the issue. Show them this log too.
