### ISSUE TITLE
Ancient Debris Exposed to Air in Nether Mineshafts

### ISSUE THREAD

**Issue by PraseodymiumSpike** [TelepathicGrunt/RepurposedStructures#229]
In Nether Mineshafts, occasionally, Ancient Debris can be found exposed to Air. Ancient Debris is never supposed to spawn exposed to Air.

**Comment by TelepathicGrunt** [comment]
Actually, this is intentional. I deliberately put the Nether Mineshafts in a later generation stage so that they are spawned after Ancient Debris so that it can have exposed Ancient Debris and makes exploring the Mineshafts actually worthwhile. 

If you do not like this, you can use a datapack and override the structure json file to move the Mineshafts to an earlier generation stage so that they spawn before Ancient Debris instead

https://github.com/TelepathicGrunt/RepurposedStructures/blob/a54576e155930c03dd0cd1b15d9ea1f691067716/src/main/resources/data/repurposed_structures/worldgen/structure/mineshaft_crimson.json#L6
