### ISSUE TITLE
Cannot connect after installing on server

### ISSUE THREAD

**Issue by MattyExie** [TelepathicGrunt/RepurposedStructures#23]
11.09 11:23:01 [Server] User Authenticator #2/INFO UUID of player _Beasty is 5105a3ca-9777-4776-b6a6-fe66f472ce01
11.09 11:23:02 [Disconnect] User com.mojang.authlib.GameProfile@56a36a7b[id=5105a3ca-9777-4776-b6a6-fe66f472ce01,name=_Beasty,properties={textures=[com.mojang.authlib.properties.Property@381ec735]},legacy=false] (/76.65.80.155:53035) has disconnected, reason: Disconnected

This had happened to my test person

**Comment by TelepathicGrunt** [comment]
can you get me the latest.log file? That line of code really doesn't say anything. if you can get me the latest.log from the server and the person that was disconnected, it'll really help!

**Comment by MattyExie** [comment]
[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures/files/5210385/latest.log)

**Comment by MattyExie** [comment]
Waiting to grab the log from him

**Comment by MattyExie** [comment]
[latest (1).log](https://github.com/TelepathicGrunt/RepurposedStructures/files/5210417/latest.1.log)

**Comment by MattyExie** [comment]
Thats his

**Comment by MattyExie** [comment]
He was able to log in fine after downloading this mod into the client, but without it, disconnect

**Comment by TelepathicGrunt** [comment]
Hmm. vanilla players connecting to servers with my mod worked in the past. I'll try and setup some tests to see if the registry changes in 1.16+ is what is causing this issue. Though if my tests works in 1.16+ with vanilla connecting to a server with my mod, then the issue is something else.

I did see that there's a lot of `Parsing error loading` stuff on the server where it's failing to read loottables and recipes which might actually be a hint of a bigger issue. I seen something similar to that where someone's mod was calling DynamicRegistries class before the world was made which broke the registries for nearly all mods and causes log errors, missing biomes, and other chaos. 

Give me a bit of time and I'll see what I find!

**Comment by MattyExie** [comment]
Oh? Alright, if you can find literally anything wrong with the modpack, please let me know.

**Comment by MattyExie** [comment]
Most of the Parsing error stuff I'm looking at refers to Biome's O plenty, but not having it installed server wise. So maybe it's just trying to pull data thats there?

**Comment by TelepathicGrunt** [comment]
Ok I was able to access a server using Repurposed Structures with a vanilla client. Looks good on my end.
![image](https://user-images.githubusercontent.com/40846040/92995326-98135480-f4d0-11ea-80d3-a9b0c19c0ace.png)

Though I'm not sure Biome o Plenty is the real issue. I have a thought but I need help to run 1 more test. Can you put on this beta version of Blame onto the server and then restart the server with all the mods on that caused the issue? Then get me the latest.log file from the server. I upgraded Blame to detect if another mod is classloading DynamicRegistries way too early and is killing the registry for everyone. It'll also show which mod is doing it too!
[blame-1.16.2-1.2.0b.zip](https://github.com/TelepathicGrunt/RepurposedStructures/files/5212657/blame-1.16.2-1.2.0b.zip)

If this doesn't work, then I'm definitely running out of ideas

**Comment by Chrysarius** [comment]
I also encountered this bug today on v2.0.6 for 1.16.1. Can't use Blame because it doesn't have back-compat for 1.16.1, but here are mine.

Client
[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures/files/5214048/latest.log)

Server
[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures/files/5214051/latest.log)

**Comment by TelepathicGrunt** [comment]
v1.16.1 repurposed structures is sadly no longer supported. I keep my mods on the latest mc version (1.16.2/1.16.3) to help reduce my workload as I'm already way behind on my mods. 

Though that is interesting you're getting the bug in 1.16.1. hmmm.

Was the server or the client using Optifine in any way? I did hear from some people that Optifine breaks worldgen mods in 1.16+ as it breaks the forge registries. If so, does the crash go away when Optifine is removed

**Comment by Chrysarius** [comment]
Yeah, that's understandable. I have to play on 1.16.1 if I want to use the bigger mods like Immersive Engineering and Mekanism so I can't really update quite yet.

As for the optifine, unfortunately it breaks IE multiblock models among other things so it's not on client or server :/

**Comment by TelepathicGrunt** [comment]
@Chrysarius Wait, do you have C.O.M.B.A.T. mod on? The original poster replied to me saying he narrowed the issue down to that mod and I want to see if that's also what is causing your issue too

**Comment by Chrysarius** [comment]
@TelepathicGrunt I do not. I also definitely thought one of the latest.log files included a mod list but I guess not. Oops. Sorry. 
Here's what I'm running; I used '/forge mods' on the server and a singleplayer world respectively to get the lists.

server
[modlist.txt](https://github.com/TelepathicGrunt/RepurposedStructures/files/5220837/modlist.txt)

client
[modlist.txt](https://github.com/TelepathicGrunt/RepurposedStructures/files/5220869/modlist.txt)

**Comment by TelepathicGrunt** [comment]
I setup a 1.16.1 server and uhh yeah it's my mod. Oops

Strangely, the issue is only on 1.16.1 but not on 1.16.2+ which I am assuming is because of the massive change to how registries work that Mojang did in 1.16.2.

What you could do is put repurposed structures on the client for 1.16.1. But once you move onto 1.16.2, it should be safe to keep it only serverside. This is so weird but then again, 1.16.1 was shuffling things around to setup for 1.16.2 so it's kind of not surprising it broke my mod lol.

I'll put a warning on the 1.16.1 jar about this but thank you both for reporting this! If this issue pops up in 1.16.2 or 1.16.3, don't hesitate to re-open this report or make a new one!
