### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Kasia1403** [TelepathicGrunt/RepurposedStructures#230]
To backport to Minecraft 1.12.2 Forge 2860 please !

**Comment by TelepathicGrunt** [comment]
Sadly, I do not do backports. It's too much work and 1.12's worldgen code is horrible and I never ever want to touch that again lol. If another modder wants to backport my mod, they can do so! But would require a complete rewrite of the mod from the ground up to the point it is an entirely different mod. Especially since the jigsaw structure system doesn’t exist at all in 1.12
