### ISSUE TITLE
[CRITICAL BUG] Previous server world cannot save progress.

### ISSUE THREAD

**Issue by Cixon** [TelepathicGrunt/RepurposedStructures#24]
![Screenshot (379)](https://user-images.githubusercontent.com/69068153/94580433-899e9a00-023f-11eb-8ad8-3f2ad9fcb383.png)

Log spam after removing repurposed structures followed by a bricked world. Changed game version and no solution found.

**Comment by TelepathicGrunt** [comment]
This is because of this mojang bug. No structure mod can be removed or else the game is unable to parse the chunk's structure data and just dies. 
https://bugs.mojang.com/browse/MC-194811

Forge would have to be the one to patch this sadly. I cannot include a patch for it in my mod as the patch won't work if my mod is removed. Sorry :(

I thought I had a warning about this on the mod page but it seems I might've accidentally removed it when I updated the curseforge descriptions of both the fabric and forge version of my mod. Fabric API released a fix for the mojang bug so that page didn't need the warning anymore. I'll add it back to the forge page

**Comment by TelepathicGrunt** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/7363
Found an issue report on Forge's github you can check out too to keep up with the progress on this issue. For now, you'll have to keep on Repurposed Structures to keep playing your world.

**Comment by TelepathicGrunt** [comment]
Here, this person just made a mod to fix this problem as Forge may not be fixing this anytime soon.

**For anyone else also reading this, put on this mod and keep it on to save your worlds when updating to 1.16.3 or removing structure mods!
https://www.curseforge.com/minecraft/mc-mods/missing-structure-fix**

**Comment by TelepathicGrunt** [comment]
v35.1.0 of forge patched this bug! I'll close this issue report now
