### ISSUE TITLE
Crash when a End Outpost is founded

### ISSUE THREAD

**Issue by Jukabofy** [TelepathicGrunt/RepurposedStructures#242]
https://www.curseforge.com/minecraft/texture-packs/repurposed-structures-savage-ravage-datapack
I'm using this datapack, it doesn't crash it just freezes the world
here is my log, it shows something about three entities
[debug.log](https://github.com/TelepathicGrunt/RepurposedStructures/files/9997707/debug.log)

[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures/files/9997706/latest.log)

**Comment by TelepathicGrunt** [comment]
It is hard for me to read the log on mobile but there’s no stacktrace or crash from what I can see. And since you said the world freezes, that means you got a deadlock or code that is stuck. The log files won’t help here. Instead, a thread dump will be needed. Can you check if spark can do a thread dump or use VisualVM to do so? 

The thread dump should be done as soon as you notice the game locked up. But some people had trouble setting up VisualVM to detect the game tho but here’s the link for and video on how to use it if you give it a shot
https://visualvm.github.io/download.html

https://streamable.com/n4hw6w

Once I have the thread dump, it’ll tell me what code is stuck and from what mod. Otherwise, if you can’t do the thread dump, please give me your entire modpack instance so I can have an easier time reproducing and narrowing down the issue

**Comment by TelepathicGrunt** [comment]
I just tested Repurposed Structures, Savage and Ravage, and the datapack all alone and I was able to go to an End Outpost just fine. It sounds like you got a different mod in the pack that's breaking for whatever reason but yeah, the thread dump will probably be the easiest way to find the problematic mod.
![image](https://user-images.githubusercontent.com/40846040/201561846-4bc3960c-35b8-41e3-9b67-ebd06227bb35.png)

**Comment by TelepathicGrunt** [comment]
Closing as it has been over a week with no response

**Comment by Jukabofy** [comment]
LOL
anyways, it seems fixed with the last update 
![2022-12-02_15 35 53](https://user-images.githubusercontent.com/87483832/205382578-01d09fc1-7f68-464f-b5a3-9a278c9193a3.png)
