### ISSUE TITLE
Deep Dark Structures

### ISSUE THREAD

**Issue by badooga** [TelepathicGrunt/RepurposedStructures#246]
Some structures repurposed for usage in Deep Dark caves (using a deepslate palette) would be cool. In particular:

- Ocean Ruins
- Outposts
- Jungle Pyramids?

Instead of mobs, they could potentially spawn with a warden pre-summoned.

**Comment by TelepathicGrunt** [comment]
Spawning in caves is not an easy thing to accomplish with structures and also runs the risk of performance issue as I have to scan for the cave. 

Ancient cities are massive so they have a good chance of interrupting a cave system to be discoverable. Smaller stuff like outposts, ruins, or temples would be next to impossible to find unless I manually scan and stick them into caves and even then, they will still be very hard to find. 

The Underground Bastion works because it is a high loot, large structure that I have explorer maps that locate it from wandering traders/land ruins. The three structures you proposed are too small and low loot that it isn’t worth making an explorer map to point to them. 

Also, I am not a fan of outposts underground. That won’t look good in my opinion and cannot be filled with pillagers as they cannot survive sculk

**Comment by gamma-02** [comment]
Flip the outpost upside down and name all the pillagers dinnerbone
