### ISSUE TITLE
No structure or feature spawns with Biome o Plenty worldtype.

### ISSUE THREAD

**Issue by tikiMC** [TelepathicGrunt/RepurposedStructures#25]
Lots of features don't seem to be spawning with the newest version of biomes o' plenty. All the village variants, outposts, temples, shipwrecks from just the little testing I did.

**Comment by TelepathicGrunt** [comment]
What mods do you have on? It works perfectly fine when I tested it alone

**Comment by tikiMC** [comment]
whats the best way to send you that list?

**Comment by TelepathicGrunt** [comment]
Oh I see you mentioned Biomes o Plenty. Yeah they have a bug where they aren't using the biome registry correctly in their biome provider. So they are spawning biomes that does not have any mod's features, structures, etc if those other mods were using the BiomeLoadingEvent form Forge.

https://github.com/Glitchfiend/BiomesOPlenty/issues/1691

You'll have to keep watch on that issue report I made to them to know when it is fixed. :)

**Comment by tikiMC** [comment]
okay thanks, hopefully they fix that, great mod btw :)

**Comment by TelepathicGrunt** [comment]
@tikiMC I was testing earlier and it turns out Repurposed Structures's structures and features are spawning. It's just the /locate command is not working due to that bug mentioned. So yeah, you can use our mods together but you'll have to find the structures by good old fashion exploring lol

![image](https://user-images.githubusercontent.com/40846040/95511322-4eaa0e00-0985-11eb-8e70-4c4edeed046c.png)

**Comment by TelepathicGrunt** [comment]
I almost forgot about this! BoP closed their issue report and their latest release now makes the /locate command work again! Now you can use the commands to find modded structures in BoP once more
