### ISSUE TITLE
Add a library-only version

### ISSUE THREAD

**Issue by skerit** [TelepathicGrunt/RepurposedStructures#251]
It would be great if there was a library-only version of your mod.
I use it for all the great new features you've added to the structure configuration, but I don't actually want all the new pre-made structures (not because they're not good of course :) They just don't fit the theme of my world)

**Comment by TelepathicGrunt** [comment]
I am not really looking to do and maintain a lib but there is another mod that was supposed to be the lib you’re describing. It is Structure Toolkit. You can reach out to that dev and ask them to update that mod. Otherwise, you can disable all of RS’s structures and features and just use the various options my mod provides

Structure toolkit: https://www.curseforge.com/minecraft/mc-mods/structure-toolkit
