### ISSUE TITLE
New `v*-with-original-monuments` versions for Modrinth data packs should be their own project

### ISSUE THREAD

**Issue by Sammcb** [TelepathicGrunt/RepurposedStructures#261]
I saw that recently, projects like the [RS Better Oceans Compat data pack](https://modrinth.com/datapack/repurposed-structures-better-ocean-monuments-compat/versions) had new versions released. There were two new ones in the better oceans and better witch huts data packs: `v*` and `v*-with-original-monuments`. I was wondering if the `v*-with-original-monuments` versions could be made into separate data pack projects as it would be much easier to automate update checks (such as from a CLI tool) for those vs. trying to figure out if new versions added to the existing data packs are what a user wants (continuing their use of the regular `v*` version or the versions with original monuments). Thanks so much (and I'm very excited to have the data packs with the original monuments available)!

**Comment by TelepathicGrunt** [comment]
No. I’m not going to split them out into their own projects. That’s too much project spam and the datapacks are extremely similar to the original. Doesn’t make sense to force players to look for some other project for what they want when it can be kept in the same place as the original. Since the original project is where they will be going anyway for the datapack, that’s where they should see all their options. 

Idk how your CI checks works but there likely is no best solution. Though these compat datapacks really don’t change much as should be fully solid now so you shouldn’t be constantly checking if you should update them anyway. There likely will be no more updates till 1.20 and that’s assuming if Mojang changes worldgen enough that it would indeed break the datapacks

I’ll try to upload the non-original-style datapacks last so the 2 style one gets buried under it going forward if that’s your concern
