### ISSUE TITLE
1.19.2 Dedicated Server - Datapack Crash with ``Repurposed_Structures-Better_Nether_Fortress_v2.zip`` and  ``YungsBetterNetherFortresses-1.19.2-Forge-1.0.5`` on ``repurposed_structures_forge-6.3.18+1.19.2.jar``

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TelepathicGrunt/RepurposedStructures#271]
Forge 43.2.7

Here is the debug and latest Log - I hope this helps :D https://gist.github.com/P3rf3ctXZer0/8e61c54529a8dc209f1ca02c58d3005d

**Comment by P3rf3ctXZer0** [comment]
Some relevant information; does not crash client side.

**Comment by TelepathicGrunt** [comment]
@P3rf3ctXZer0 I just tested on server with latest repurposed structures, yungs api, yungs better nether fortress, and compat datapack. It is working for me.
![image](https://user-images.githubusercontent.com/40846040/226505777-b62d3db9-24ce-45a1-882d-d1beb5dcd9e9.png)

Looking at your log, the issue is you do not have Yung's Better Nether Fortress mod on your server. Without the mod, the compat datapack cannot work. Put on the mod and the server will work. I'll put out an update for compat datapack to fix a small tag issue I saw in logs but that doesn't prevent loading world

**Comment by P3rf3ctXZer0** [comment]
Lol I definitely had the mod so what your saying is it didn't see the mod. It doesn't matter when something breaks I just remove it.

**Comment by TelepathicGrunt** [comment]
Are you sure you had it on? And the correct version (not Fabric) in the mod folder on server? Cause this part at top of your log is how I know the mod wasn't loaded. I searched "yung" but did not see Nether Fortress 
![image](https://user-images.githubusercontent.com/40846040/226507049-de575040-571c-4eaf-bb62-5fbc721c0963.png)

If mods aren't loading on the server, you got big problems lol.

**Comment by P3rf3ctXZer0** [comment]
Yeah also it was just the one mod happened everytime I started once I removed Nether Fortress Datapack it worked fine. Yungs Nether fortress works by itself - not with data pack also to hot load things I am using ``
global_packs-forge-1.19.2-1.14.2_forge.jar`` so I don't need to change it to the world ever.
