### ISSUE TITLE
[Not Lethal Issue]1.19.2 - Failed to Read Ancient City Structure ``Repurposed_Structures-Better_Monuments_v5-With_Original_Monuments.zip`` and ``YungsBetterOceanMonuments-1.19.2-Forge-2.1.0.jar`` on ``repurposed_structures_forge-6.3.18+1.19.2.jar``

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TelepathicGrunt/RepurposedStructures#272]
Forge 43.2.7
https://gist.github.com/P3rf3ctXZer0/35aa4d23a2b8e3bcb937640095ac4b9d

**Comment by TelepathicGrunt** [comment]
This appears to be a vanilla bug I inherited because I copied their ancient city layout exactly. Vanilla Ancient City template pool targets "minecraft:ancient_city/walls/intact_horizontal_wall_stairs_5" nbt file.
https://github.com/misode/mcmeta/blob/8252860f9beb6696824161b8b4b04ada5ae939dd/data/minecraft/worldgen/template_pool/ancient_city/walls/no_corners.json#L60

However, vanilla does not have that nbt file at all:
https://github.com/misode/mcmeta/tree/data/data/minecraft/structures/ancient_city/walls

So the piece doesn't spawn since it doesn't exist. I'll just remove that entry from the template pool is all. The Ancient City structure still generates exactly as Mojang seems to intend so mine is mimicking it perfectly. Perhaps too perfectly.

Luckily Mojang has a bug report for it already https://bugs.mojang.com/browse/MC-249771

**Comment by TelepathicGrunt** [comment]
Was fixed in latest updated
