### ISSUE TITLE
Failed to Create Structure

### ISSUE THREAD

**Issue by NoLiver92** [TelepathicGrunt/RepurposedStructures#273]
Minecraft Version: 1.19.2
Modpack: Dreamcraft (Fabric)
Mod Version: 6.3.20
Other Mod with Issues: Fabric Waystones 3.0.5

When exploring the world the server lagged and then crashed due to the watchdog timer, the area was on chunk generation.
I managed to get back in and the server took a long time to respond and then posted the following statement in chat.

![minecraft issue](https://user-images.githubusercontent.com/4210553/229872321-af20475f-f9cf-4cfd-bb61-1fabd7a6da32.PNG)

I have looked at fabric waystones mod and it doesnt have a mossy stone vilage waystone in the waystones mod (cant find it on the /give command)
I went to the location and it wasnt near where the player was and i didnt see a structure generated (wasnt in a jungle and there wasnt a visible village there)

**Comment by TelepathicGrunt** [comment]
I highly doubt it’s RS issue nor waystone. That message printed after the structure layout was already finalized. 

Please share the crashlog after the watchdog kills the server

**Comment by TelepathicGrunt** [comment]
Also, Fabric Waystones does have a mossy stone bricks Waystone piece as shown here which was tried to be injected into the rs village but failed for whatever reason https://github.com/LordDeatHunter/FabricWaystones/blob/master/src/main/resources/data/fwaystones/structures/mossy_stone_brick_village_waystone.nbt

**Comment by TelepathicGrunt** [comment]
@NoLiver92 geesus, Dreamcraft fabric 1.19.2 is using such an old and outdated repurposed structures version. I updated repurposed structures and waystones. Then teleported to the Jungle Village and no deadlock. Village spawns fine. Even has a Waystone.
![image](https://user-images.githubusercontent.com/40846040/230623230-f4b7850d-e599-49a5-980c-f1b7c3cdcaa0.png)

So i guess just update these two mods (Also update my Bumblezone mod as well in the pack).

Dreamcraft seems to be a collection of outdated mod versions and is not updating them to fix many issues. I would not recommend this pack tbh until they update most of the mods as us devs push out updates all the time to fix various issues. The deadlock you had experienced is not likely to be RS or Waystone but it might had already been fixed by a different mod int heir newer version that Dreamcraft isn't using.
