### ISSUE TITLE
1.19.2 | Weird Generation (Yung's Better Nether Fortress Compat Datapack)

### ISSUE THREAD

**Issue by szunakabeats** [TelepathicGrunt/RepurposedStructures#274]
![2023-04-06_13 21 01](https://user-images.githubusercontent.com/88375166/230362730-10b221a8-4798-4a0c-a300-812fc430d33c.png)

**Comment by TelepathicGrunt** [comment]
@szunakabeats I will need your full modpack and datapacks. You didn't edit the processor right? Because when I test with datapack and the two mods alone, the pillars are created correctly.

![image](https://user-images.githubusercontent.com/40846040/230381638-64ef4c2e-d917-452e-b55b-9ee1b0f4c695.png)

In your picture, the red wool/black wool under the pieces that should be creating the pillars appears to be replaced with Muddy Mangrove Roots or Mud. Which should *not* be possible unless you replaced the bygonenether:jungle\fortress processor list itself to mess with these blocks or whatever. That or another mod is changing the blocks in the structure before my processor list reaches it.

Without the modpack instance with all the mods and datapacks, I cannot troubleshoot further as to who is interfering

**Comment by TelepathicGrunt** [comment]
Ignore my now deleted comment. I was looking at wrong datapack. I know where issue is

**Comment by szunakabeats** [comment]
okay no problem, if u need any logs or something let me know !

**Comment by TelepathicGrunt** [comment]
v4 of datapack is now out to fix pillar supports not spawning

https://www.curseforge.com/minecraft/texture-packs/repurposed-structures-yungs-better-nether-fortress/files/4478435
https://modrinth.com/datapack/repurposed-structures-yungs-better-nether-fortress-compat/version/I4ZwYyOv
