### ISSUE TITLE
Datapack Validation Failed on 1.19.2 all Yung's compat structures

### ISSUE THREAD

**Issue by Traehgniw** [TelepathicGrunt/RepurposedStructures#276]
All the compatibility packs for Yung's structures and RS are failing to validate for me on 1.19.2 Fabric. I have Yung's mods. I have not tested desert temple because that is the one Yung's mod I don't have.

If added to the game via Paxi these datapacks cause the game to crash when clicking on the New World option, claiming an error with a generic jigsaw structure.

**Comment by TelepathicGrunt** [comment]
Please give me the latest.log after getting the crash. Also make sure you updated repurposed structures, Yung’s mods, and Yung’s api

also I need to know what modloader you’re on. I tested better nether fortress just yesterday and that was fine https://www.curseforge.com/minecraft/texture-packs/repurposed-structures-yungs-better-nether-fortress#c8

**Comment by Traehgniw** [comment]
As mentioned it's Fabric 1.19.2. I used fresh downloads of all the Yungs and RS stuff.

Here is the crashlog from putting the RS datapacks into Paxi (a universal datapacks mod): https://mclo.gs/4HaxEXG

**Comment by TelepathicGrunt** [comment]
`Caused by: com.google.gson.JsonParseException: Error loading registry data: Unknown registry key in ResourceKey[minecraft:root / minecraft:worldgen/structure_type]: repurposed_structures:generic_jigsaw_structure`

While the log seems to try to pin the blame on me, this structure type is registered and does exist. At no point should it ever not exist: 
https://github.com/TelepathicGrunt/RepurposedStructures/blob/8bd71a3485c0de69db22c748ac706ed7d1dc1a97/src/main/java/com/telepathicgrunt/repurposedstructures/modinit/RSStructures.java#L33

Furthermore, I put on latest version of all Yung's mods, latest version of Repurposed Structures, and latest version of all my compat datapacks with Yung's mods. Then entered a world with the datapacks in Paxi's folder. No issue
![image](https://user-images.githubusercontent.com/40846040/230770717-f506f9d5-6b71-4b6f-8bac-a81f3258c7fc.png)

So to me, sounds more like your modpack is broken in a way that another mod broke datapack loading or something. You can zip up and send me your modpack instance by google drive or dropbox and I'll try and pin down the true offender as this is not an RS issue as far as I can see

**Comment by Traehgniw** [comment]
https://www.dropbox.com/s/234n0l7qunsbpmk/OriginsCustomized-7.2.0.zip?dl=0

Here's the link! The RS datapacks are not currently in Paxi's Datapacks folder, they're next to it in the Paxi configs folder. Move them to the 'datapacks' subfolder of the Paxi folder for the crash-on-clicking-create-world behaviour, or try to put them into Datapacks on creating a world to get the "datapacks failed to validate" error.

**Comment by TelepathicGrunt** [comment]
![image](https://user-images.githubusercontent.com/40846040/230775137-379a8cac-5cb9-4217-a927-300e37adc490.png)

You had Repurposed Structures disabled. The datapacks requires Repurposed Structures to be active (and also the compat mod to be active as well)

After that, remove the RS - Yung Better Dungeons datapack because you do not have Yungs Better Dungeons mod on so that datapack will error (Unless you put on that mod as well)

 I enabled RS jar and remove  RS - Yung Better Dungeons datapack and your modpack now works and I can enter worlds. Issue is just how your modpack is setup. Do the changes I listed and you should be good to go

**Comment by Traehgniw** [comment]
uytrerb Why is that disabled??? It's freshly installed how did I manage to disable it

thanks
