### ISSUE TITLE
Mod repurposed_structures is shipping outdated structure files, which can cause worldgen lag

### ISSUE THREAD

**Issue by Reshy** [TelepathicGrunt/RepurposedStructures#284]
[29May2023 08:06:15.611] [Worker-Main-17/WARN] [ModernFix/]: Mod repurposed_structures is shipping outdated structure files, which can cause worldgen lag; please report this to them.

Not sure if this is an issue, but it showed up in my logs during testing.  There was also a gap in the world that occurred.  Might be related.

**Comment by TelepathicGrunt** [comment]
Not an issue.  RS files are close enough to updated in 1.19.2 if not already fully so and should not cause any DFU lag. in 1.19.4+, it is pointless as DFU is optimized then to be blazing fast

**Comment by TelepathicGrunt** [comment]
For anyone else reading this, here's the full info. I actually already ran 1.19.2 RS files through Structure Fixer https://github.com/jaskarth/structure-fixer So RS files are already updated to 1.19.2 for DFU as seen here: https://github.com/TelepathicGrunt/RepurposedStructures/commit/bf3a50fba6fb2bcd8ff0eaaf6f98d456ed74f8a7

If any files are missed, ModernFix should at least print exactly what NBT file. The only 'outdated' nbt files there are would be the compat datapacks and I am not going to manually update all 20+ compat datapacks I have since this DFU thing was never a problem for them. This is because the current compat datapacks were made in like 1.19.0 at the earliest for 1.19.2 so there's like no DFU work to do on them due to them being so new.

**Comment by TelepathicGrunt** [comment]
Embeddedt just mentioned the debug.log file holds the actual NBT files that ModernFix says is outdated. If the NBT files there list the datapack RS NBT files, ignore it. If it lists NBT files in the base RS mod, lmk as I missed those files
