### ISSUE TITLE
nether bug over 156 height

### ISSUE THREAD

**Issue by MrJorman** [TelepathicGrunt/RepurposedStructures#286]
![image](https://github.com/TelepathicGrunt/RepurposedStructures/assets/55187962/b57d7409-1e7c-4626-8db5-768d6a124070)
Bedrock nether spawn more structures...... y=156+
![image](https://github.com/TelepathicGrunt/RepurposedStructures/assets/55187962/91e14868-2c93-43e2-b4f7-c0aa821e4106)

**Comment by TelepathicGrunt** [comment]
Do you have the RS-Quark compat datapack? If so, this is probably another change of their’s. They made the datapack specifically for usage with Amplified Nether mod

See this: https://github.com/TelepathicGrunt/RepurposedStructures/issues/285

otherwise, I need an export of your modpack so I can download it and investigate. RS alone will not do this

**Comment by MrJorman** [comment]
yes. i use Quark Compat datapack.

**Comment by MrJorman** [comment]
Fix. Quark compat broken mod Lootr and other.
