### ISSUE TITLE
[NotABug] Pyramid generation issue

### ISSUE THREAD

**Issue by MbtMarco** [TelepathicGrunt/RepurposedStructures#295]
### I don't know if this is normal.
![2023-08-10_10 10 51](https://github.com/TelepathicGrunt/RepurposedStructures/assets/124934175/f83b4d67-e89d-4034-a4fe-2b61b69036e3)

**Comment by TelepathicGrunt** [comment]
This tells me nothing btw. You have to tell me exactly what biome the structure is in and more pictures around. But otherwise, pyramids will sample the land at each of their corners and average it for the height to spawn at. This way, they can get buried similar to how vanilla desert temples do. So if in the picture, some corner is super low, that would pull down the average height and bury the pyramid which is fine. The only thing i want to know more about is the biome in this area

**Comment by MbtMarco** [comment]
Maybe it is a problem related to how structures work in Minecraft? Anyway that pyramid I sent you I don't have the world anymore (I was trying a modpack). I can send you other images that can help you, I don't know. I didn't know if it's a problem with your mod or how the structures work in Minecraft I wanted to understand it better.

**Comment by MbtMarco** [comment]
![2023-08-10_12 17 58](https://github.com/TelepathicGrunt/RepurposedStructures/assets/124934175/522c5dd6-3655-4693-9c8c-40c9eda60b5d)
![2023-08-10_12 20 39](https://github.com/TelepathicGrunt/RepurposedStructures/assets/124934175/462a0d3c-e433-47f8-8668-96f5270aa4b9)


At this point I think it's a Minecraft issue, right?

**Comment by TelepathicGrunt** [comment]
Buried desert temples in minecraft are intentional. I tried to recreate the effect by averaging the height of the land at each corner of my pyramid to spawn at. Since vanilla desert temples won’t spawn below sea level, I capped my structure to not spawn below sea level either. No bug there. Structure is spawning perfectly fine height wise. 

Unless there’s something else bothering you. If so, you need to explain what it is. Cause the pictures looks fine to me.

However, the pyramid is a flower forest biome pyramid but I see snow in the first picture. Was there a flower based biome nearby or is it entirely in this snowy biome? (Hence why I wanted to know more about the biome so I can investigate why it is in the snowy biome)

**Comment by TelepathicGrunt** [comment]
Biomes the flower forest pyramid can spawn in: 
https://github.com/TelepathicGrunt/RepurposedStructures/blob/1.20-Arch/common/src/main/resources/data/repurposed_structures/tags/worldgen/biome/collections/floral.json

**Comment by MbtMarco** [comment]
> Buried desert temples in minecraft are intentional. I tried to recreate the effect by averaging the height of the land at each corner of my pyramid to spawn at. Since vanilla desert temples won’t spawn below sea level, I capped my structure to not spawn below sea level either. No bug there. Structure is spawning perfectly fine height wise.
> 
> Unless there’s something else bothering you. If so, you need to explain what it is. Cause the pictures looks fine to me.
> 
> However, the pyramid is a flower forest biome pyramid but I see snow in the first picture. Was there a flower based biome nearby or is it entirely in this snowy biome? (Hence why I wanted to know more about the biome so I can investigate why it is in the snowy biome)

Okay, I got it. Regarding the biome with snow, it's a mod that if you would like to support it would be very cool, it's called [Regions Unexplored](https://modrinth.com/mod/regions-unexplored). It's a very good replacement for BYO for version 1.20.(1).

**Comment by IntM4rco** [comment]
The pyramid was spawned in a biome next to the mod.
