### ISSUE TITLE
Add full-compatibility with Regions Unexplored mod

### ISSUE THREAD

**Issue by MbtMarco** [TelepathicGrunt/RepurposedStructures#297]
https://modrinth.com/mod/regions-unexplored

Please 🫠

**Comment by TelepathicGrunt** [comment]
Repurposed structures is already mostly compatible with that mod because I use biome tags and they add their biomes to biome tags. 

Extra compat to get my structures to spawn in a bit more of their biomes is in this commit. The extra compat is only going to be for 1.20.1 when I release the next update for that mc version
https://github.com/TelepathicGrunt/RepurposedStructures/commit/23c0231b5e5f9f3beafe32d18017806f349730f9

**Comment by MbtMarco** [comment]
Ty 😁
