### ISSUE TITLE
'Old Generation types'  Warning of server lags

### ISSUE THREAD

**Issue by LiAuTraver** [TelepathicGrunt/RepurposedStructures#300]
When i and my friend entered the structure, the server become extremely slow and maybe it caused several lacks. Thus i use the modernfix mod and it shows 'the structure repurposed structure contains a older generation type, which may cause lags.' but we certainly love your mod, and could this problems be fixed?

**Comment by TelepathicGrunt** [comment]
It’s not DFU as the nbt files it talks about are very small and won’t cause DFU to hang. Also, DFU is ran when the nbt file is first loaded to place into world. Not after worldgen when you’re entering a structure so your issue is not worldgen related.

Please run spark for 60 while experiencing the slowness. Have spark run on the server thread if you’re having tps issue or in render thread if you’re having fps issue. Then share the spark report as that will tell you exactly what the game is slowed on

**Comment by LiAuTraver** [comment]
Sorry for the inconveniences and my late response. I'm not a naive Eng speaker and had little knowledge in JAVA programming, so in fact I could hardly understand your exact meaning (gash, I do not even know how the nbt or dfu exactly function). In the condition that the warning message from modernfix may be incorrect. And I will close the issue, and I apologize for my criticism on your mod.

**Comment by TelepathicGrunt** [comment]
This is the Spark mod that will help you find what is lagging easier: https://www.curseforge.com/minecraft/mc-mods/spark

hope that’s helps!
