### ISSUE TITLE
better strongholds compat not working

### ISSUE THREAD

**Issue by Boba194230** [TelepathicGrunt/RepurposedStructures#301]
_few things, first, can you please make a separate issue report instead of clogging up this one? This issue report is for documenting datapack to make, not for support.

Second, the datapack works for me so it’s likely something that you’re doing. There is an order to datapacks and you’ll want the datapack you put on to be after the mod’s own internal datapacks. So that the datapack overrides the mod’s files and not other way around_

_Originally posted by @TelepathicGrunt in https://github.com/TelepathicGrunt/RepurposedStructures/issues/113#issuecomment-1725043834_
            
            
Sorry I saw someone else asking for help in that thread so I thought I would too. How exactly would I go about changing the load order since I’m using global packs? Shouldn’t it automatically be after?

**Comment by Boba194230** [comment]
Also I found the command to change load order but I’m not exactly sure how to change the mods internal stuff to load before as I’m pretty sure all the data packs get loading after my mods when I check the servers console

**Comment by Boba194230** [comment]
I've done the command to change the load order and put it last and reloaded and generated a new one and it still didn't work. Odd

**Comment by Boba194230** [comment]
Maybe modern fix causes incompatibilities?

**Comment by Boba194230** [comment]
Just disabled and didn't change anything

**Comment by Boba194230** [comment]
Disabled the stronghold remover datapack and still doesn't work :/

**Comment by Boba194230** [comment]
I guess next I’ll try moving from my dedicated server to just my client and start testing mods 1 by 1 and see what causing it :/

**Comment by TelepathicGrunt** [comment]
I am using Global Packs mod and I put my datapack in the resourcepacks folder. 
![image](https://github.com/TelepathicGrunt/RepurposedStructures/assets/40846040/10affd5f-d761-400c-88ba-f668f2b83ad0)

Yung's Better Strongholds turns off the vanilla strongholds. It turns out that Stellarity and Taverns both modify the vanilla strongholds which imo, is the wrong way to do it. What they should had done is disable the vanilla stronghold and provide their own stronghold as their own structures. I made this small datapack that disables yung's strongholds, move stellarity and taverns into their own separate structures, and made eyes of ender be able to find those new strongholds.
[disable_yung_enable_taverns_and_stellarity.zip](https://github.com/TelepathicGrunt/RepurposedStructures/files/12695860/disable_yung_enable_taverns_and_stellarity.zip)

Here's a test with Repurposed Structures, Better Strongholds, Stellarity, Taverns, Repurposed Structures - Better Strongholds Compat Datapack, and the new datapack i just posted above:
![image](https://github.com/TelepathicGrunt/RepurposedStructures/assets/40846040/449974d0-cc4f-4368-b6d1-0776767f7030)
![image](https://github.com/TelepathicGrunt/RepurposedStructures/assets/40846040/6655ddb6-044f-4279-8b8b-95ada8a113fa)
![image](https://github.com/TelepathicGrunt/RepurposedStructures/assets/40846040/f8964697-4311-4acd-bad5-43522fb8aea6)
![image](https://github.com/TelepathicGrunt/RepurposedStructures/assets/40846040/0f1debbb-661e-4f5c-b99e-5563870d55e1)
![image](https://github.com/TelepathicGrunt/RepurposedStructures/assets/40846040/760ae0bc-5499-4c2a-af55-c40dfaf1fdd7)

Everything is working as expected in my testing. Only issue I see is taverns/stellarity strongholds takes so long to generate their layout that it will lag locate and eyes of ender a significant ton. Your server could deadlock as a result so locate with care with those mod's strongholds. Repurposed Structures's strongholds generates its layout super fast and shouldn't deadlock the server

**Comment by Boba194230** [comment]
It appears that it only works on my client not the dedicated server.

**Comment by TelepathicGrunt** [comment]
Closing as this was resolved. Everything should be good
