### ISSUE TITLE
Minecraft stops ticking when loading certain chunks (1.20.1)

### ISSUE THREAD

**Issue by theavandiepen** [TelepathicGrunt/RepurposedStructures#306]
This happens when both Repurposed Structures and Fabric Waystones are installed. Nothing crashes, so there's no crash report. What happens is chunks stop loading at certain spots on the map. I can still walk around but if I got too close to the edge, all mobs, villagers included, stop moving and creative commands don't do anything. If I walk across to the unloaded chunk, the world disappears entirely. If I try to walk back the way I came, I find that chunks that had loaded fine are no longer loading and if I go too far along them, the sun starts glitching.

If I remove either Repurposed Structures or Fabric Waystones, everything works as expected.

**To Reproduce**
1. Load up [this save](https://drive.google.com/file/d/1yxZg2pybWz98JdGMSczW42fUy8ZLqxAi/view?usp=drive_link) with [these mods](https://drive.google.com/file/d/1fNRIEfHp7IMbNOKa_Y0xHl6VJJ6fSnX2/view?usp=drive_link)
2. If you're not already there, teleport to 234, 71, 5644
3. Walk or fly (after going into creative mode) north/northwest until you get to a tall tower with a village and some cherry trees behind it
4. Try to go north past the village

Because this happens only in particular locations for reasons I don't understand, I don't recommend loading up the save without the worldgen mods at the very least as well as Waystones and Repurposed Structures, otherwise I'm not sure if you'll replicate the issue. 

**Technical Details**
- Repurposed Structures version: 7.1.8
- Minecraft version: 1.20.1
- Java version: 17
- Quilt version: 1.21.0-beta.5
- QFAPI version 7.4.0 & QSL version 6.1.2

Full log here: https://mclo.gs/UGBuwsN

**Notes**
I am also reporting this [in the Fabric Waystones github](https://github.com/LordDeatHunter/FabricWaystones/issues/227) just in case it's an issue on their end or something that would otherwise require collaboration between both of you.

**Comment by TelepathicGrunt** [comment]
I already have high doubts this is waystone or RS related. More likely another mod deadlocking the game. A thread dump will show exactly who it is.

The mod pack link you gave is not public. Please make it public and I will try to reproduce the issue and get a thread dump to find who is deadlocking your game

**Comment by theavandiepen** [comment]
Oh shoot, sorry about the file permissions! I’ve fixed that and you should be able to download now

The log I linked to has a thread dump in there also, in case that help too

**Comment by TelepathicGrunt** [comment]
Disable randomvillagenames and see if that fixes the issue. Their code is what is deadlocking the server thread it seems
![image](https://github.com/TelepathicGrunt/RepurposedStructures/assets/40846040/90d66af5-2bda-4b8b-b2da-15e98130ce5c)


I have tested Waystones and Repurposed Structures alone and visited all my villages and they all spawned just fine. So waystones and Repurposed Structures is alright. The issue seems to lie with randomvillagenames constantly searching for villages it seems

**Comment by theavandiepen** [comment]
It's definitely more than just randomvillagenames

In my troubleshooting, while adding mods back after removing them all, [this was the set of mods](https://drive.google.com/file/d/1P5kt-jw2a7BIPKxxuLA28yibi4r9JvTc/view?usp=drive_link), minus ModernFix, where things started becoming unplayable. (I included ModernFix in there because it does handy thread dumps in logs, which might be useful).

None of Serilum's mods are in that set- I was focusing first on worldgen mods and mods that add a lot of blocks/structures to the game. It definitely gets funkier with more mods added, but before this point, it had still been playable, even if the chunk loaded pretty slowly.

Most of the world in this save works just fine, but something about this particular spot (and another spot I found in a previous attempt with this world, before I started making backups while playing) where things just... go really really wrong

**Comment by TelepathicGrunt** [comment]
Issue seems to be that the fabric waystone json file I have them use requires the repurposed structures village to always have a waystone but the RS villages you are generating are zombie villages. So they do not get the waystone because the waystones are added to the non-zombie house pools. Repurposed structures will try 100 times to generate a layout with the required piece before giving up. You're using terrablender which is slowing down terrain gen so it slows down the overall layout gen so much that it seems stuck

I'm probably going to do a two fold fix. 1, reroll the structure start piece so it is not permanently stuck. Instead will retry into being a non-zombie village. 2. PR into Fabric Waystone to inject into my zombie village house pool as well. Maybe lower the retrying to just 40 as well

**Comment by theavandiepen** [comment]
I wondered if the zombie village had something to do with it! Testing with vanilla zombie villages didn’t really cause any noticeable issues, but that would be because a) vanilla zombie villages, not RS, and b) I didn’t also have Terrablender going at the same time

Thank you so much for all the troubleshooting you’ve done so far, and I look forward to trying out the fix!

**Comment by TelepathicGrunt** [comment]
resolved now
