### ISSUE TITLE
some problems i found

### ISSUE THREAD

**Issue by peow** [TelepathicGrunt/RepurposedStructures#307]
first of all, great mod, im playing in fabric 1.20.1

1) RS structures can overlap vanilla structures
![2023-10-22_23 56 22](https://github.com/TelepathicGrunt/RepurposedStructures/assets/105888751/a970c55d-c5fd-4e50-931b-0d2c348f119d)

here a RS mansion is generated in a vanilla village
![2023-10-22_23 57 17](https://github.com/TelepathicGrunt/RepurposedStructures/assets/105888751/f3b9853f-7d50-4c07-89fb-66539b0dfc77)

my fear with this is that some underground construction of RS will end up destroying a Stronghold portal in someone's world

2) RS structures can destroy bedrock

I found a mineshaft_nether that destroyed bedrocks underneath the nether
![2023-10-23_14 25 48](https://github.com/TelepathicGrunt/RepurposedStructures/assets/105888751/38b99691-b0b7-419e-8d84-b3e742002319)
![2023-10-23_14 26 16](https://github.com/TelepathicGrunt/RepurposedStructures/assets/105888751/76389046-0a0b-4ed8-ac84-4a043fb41b01)

and as much as it may seem like it's not because of RS, I can confirm that it is, I tested the map seed using just the Fabric API, MidnightLib and Repurposed Structures

with RS: 
![2023-10-23_14 41 23](https://github.com/TelepathicGrunt/RepurposedStructures/assets/105888751/e6d48ded-1aa3-4fe1-a888-183a6deb8bfd)

without RS:
![2023-10-23_14 38 16](https://github.com/TelepathicGrunt/RepurposedStructures/assets/105888751/48f750ad-b489-4be4-9b07-91802b4855ac)

if you want to test it for yourself here is the seed and the coordinate:

seed: 2001851741016737369

tp: /execute in minecraft:the_nether run tp @s 356.86 -8.75 165.56 230.07 -43.92

the worst case is someone falling into the void and losing all their items

3) i think has to many piglins in nether's village or has another problem causing low fps
![2023-10-24_22 38 50](https://github.com/TelepathicGrunt/RepurposedStructures/assets/105888751/c6d5a6c3-5073-4773-bb65-6841f21e100a)
58 fps

![2023-10-24_22 39 00](https://github.com/TelepathicGrunt/RepurposedStructures/assets/105888751/f8b2531c-0411-4c92-8650-47de0d6de0ee)
191 fps after i killed 19 piglins

i made a test in a world with just Repurposed Structures and FPS Display mod

![2023-10-24_22 48 38](https://github.com/TelepathicGrunt/RepurposedStructures/assets/105888751/0e31322e-113f-4d47-a916-4948f3610324)

![2023-10-24_22 48 59](https://github.com/TelepathicGrunt/RepurposedStructures/assets/105888751/4953032e-ba86-4143-bbea-48a0cf3c0683)

![2023-10-24_22 49 06](https://github.com/TelepathicGrunt/RepurposedStructures/assets/105888751/0f7d7d83-f5e0-4eb7-8f39-268cbfbc6570)
increased almost 300 fps after I killed 38 nearby piglins

if you make an update pls do to fabric 1.20.1, tx

**Comment by TelepathicGrunt** [comment]
1. This is intended and a limitation of the structure system. Vanilla woodland mansions can intersect their own villages. You can find seeds online about this so I won’t be doing any work to prevent this fusion. (Also I like fusion personally as they are rare anyway and something different to find)

2. That bedrock breaking I’ll look at but I don’t see how it is rs. Unless it is a feature spawned from the structure rather than the structure pieces themselves. 

3. Piglin lowering fps is not a repurposed structures issue. That’s vanilla. You may see similar performance issue with vanilla bastions full of piglins and such but it is not game breaking and isn't unplayable tbh. If piglins are an issue in your modpack, verify you don’t have another mod causing lag with piglins and put on some rendering optimization mods if possible. The villages in nether spawns the same amount of piglins as vanilla villages spawn villagers and it is not within scope nor possible for repurposed structures to optimize piglin rendering without just removing piglins which I do not want to do. Entity rendering optimizing mods is what you'll want to use instead.

**Comment by TelepathicGrunt** [comment]
Also, no rs structure except for underground bastions even spawns on the same y level as strongholds and strongholds spawns after most structures so their end portal won’t be eaten away at

**Comment by peow** [comment]
i see, so the bedrock issue is the only problem

**Comment by TelepathicGrunt** [comment]
Bedrock issue fixed in v7.1.10. Issue wasn't the mineshafts but instead was the nether villages/outposts mainly. It has to do with "junctions" that connect the structure pieces together not being moved properly to the correct y value that rest of the structure is at.

Thank you for reporting that!

**Comment by peow** [comment]
i thank you for taking care and always updating your mod
