### ISSUE TITLE
Constant crashing on Quilt 1.19.2

### ISSUE THREAD

**Issue by Sunconure11** [TelepathicGrunt/RepurposedStructures#309]
https://pastebin.com/TVjTNBzB

@TelepathicGrunt

**Comment by TelepathicGrunt** [comment]
I need more info. You say you are on fabric but your log shows quilt which is not the same as fabric.
![image](https://github.com/TelepathicGrunt/RepurposedStructures/assets/40846040/11159692-ff18-48a4-80fe-8881c45fda8a)

And I need to know if you were editing cartographer or wandering trader map trades. Or have another mod that does

**Comment by Sunconure11** [comment]
I'm not altering trades, but I have several mods that add their own trades.

**Comment by Sunconure11** [comment]
It happens when generating a world.

**Comment by Sunconure11** [comment]
https://gist.github.com/Sunconure11/4cc26acf72b0b5817058d36f2d010ac5

**Comment by TelepathicGrunt** [comment]
I would like to have the modpack if you can export it for me to download. You likely have a mod that is adding a null instead of an empty list for a trade level. Meaning a mod's profession or trade is broken really. They should have an empty list for every trade level. Never null

https://github.com/TelepathicGrunt/RepurposedStructures/blob/d6df89298c8b00c7dc357842e033e556c4fdc1de/src/main/java/com/telepathicgrunt/repurposedstructures/misc/maptrades/StructureMapTradesEvents.java#L49

**Comment by Sunconure11** [comment]
It's a modpack of my own making. Of note is that two mods are using either builds yet to be released to the public, or have a custom fix of my own to solve some issues with other mods. I will send you a copy via Discord, as a result.

**Comment by Sunconure11** [comment]
It's also a pretty decent-sized pack, but me and one other person are working on making it more manageable.

**Comment by Sunconure11** [comment]
It's been sent.

**Comment by TelepathicGrunt** [comment]
`[05/11/2023 21:59:26 PM] [Server thread/ERROR] RepurposedStructures ResourceKey[minecraft:villager_profession / minecraft:nitwit]=nitwit --- 3 --- {2=[com.jetpacker06.CreateBrokenBad.register.VillagerTrades$$Lambda$30927/0x0000000804c40a28@2a898fe2], 1=[]} --- [com.jetpacker06.CreateBrokenBad.register.VillagerTrades$$Lambda$30929/0x0000000804c40400@3b7e99ca]`

Seems like someone is adding trades to nitwits but they skipped trade level 0 which then breaks my mod. Since you can't trade with nitwits, seems like a bug with that Create Broken Bad mod.

**Comment by TelepathicGrunt** [comment]
Create Jetpack is releasing an update now to not add trades to Nitwits. Please update Create Jetpack and see if that resolved this problem
