### ISSUE TITLE
Mixin incompatibility with Enhanced Mob Spawners

### ISSUE THREAD

**Issue by Entoarox** [TelepathicGrunt/RepurposedStructures#32]
Mod version is `1.16.3-2.2.11`
The mod it conflicts with is https://www.curseforge.com/minecraft/mc-mods/enhanced-mob-spawners

Log file: [latest.log](https://github.com/TelepathicGrunt/RepurposedStructures/files/5444294/latest.log)

From what little I understand, both mods are trying to mess with enderman spawners and getting in eachothers way, which causes a crash as a result.

**Comment by TelepathicGrunt** [comment]
Yeah this is due to EMS using an overwrite mixin instead of an inject mixin. I made an issue report to them showing them how to fix the Mojang spawner bug properly with mixins. Basically without the mixin fix, mob spawners with mobs that can be both passive and hostile will cause the mob to not render in the spawn and fill the log with spam like insane to the point the log is massive in size

https://github.com/andersblomqvist/enhanced-mob-spawners/issues/17

**Comment by Entoarox** [comment]
Ah, thanks for the info, I'll just have to remove the spawner mod until it gets fixed then....

**Comment by andersblomqvist** [comment]
@Entoarox I've now fixed the issue which made my mod incompatible with this mod.

**Comment by TelepathicGrunt** [comment]
Awesome! Thanks! I'll close this now
