### ISSUE TITLE
Repurposed Structures: Detected a mod with a broken basalt columns

### ISSUE THREAD

**Issue by temotodochi** [TelepathicGrunt/RepurposedStructures#329]
[19:24:36] [DH-World Gen Thread[2]/WARN]: Repurposed Structures: Detected a mod with a broken basalt columns configuredfeature that is trying to place blocks outside the 3x3 safe chunk area for features. Find the broken mod and report to them to fix the placement of their basalt columns feature.

I'm using distant horizons with fabric repurposed structures 7.1.13 and there is an issue with some nether structures, i have since disabled nether structures since this log crashes DH world gen threads and causes 350+ megabyte log files in a few minutes.

**Comment by TelepathicGrunt** [comment]
Please report to the proper worldgen mod to fix their broken basalt feature. They are likely using two square placements by mistake or spreads or whatever. 

the check is required because otherwise, it would’ve crashed the code if I didn’t return early
https://github.com/TelepathicGrunt/RepurposedStructures/blob/8c0e38008be4ed2984a151437bb3928741bb6cfd/common/src/main/java/com/telepathicgrunt/repurposedstructures/mixins/features/NoBasaltColumnsInStructuresMixin.java#L38

I won’t be disabling this logging because the misplaced basalt feature is broken and can cause issues. It needs to be addressed in the problematic mod instead of hiding the issue

if you list out all the worldgen mods/datapacks you’re using, we can start narrowing down which one is the issue

**Comment by TelepathicGrunt** [comment]
Closing as no new info or response after a whole week. Cannot proceed with troubleshooting any further.

**Comment by TelepathicGrunt** [comment]
Talked with some people on discord. Distant horizon may be doing something weird with chunks that puts them in a weird chunkstatus state they shouldn’t be in when generating features

**Comment by TelepathicGrunt** [comment]
Documentation for future reference if needed in case another mod causes similar chunkstatus issue:
![image](https://github.com/TelepathicGrunt/RepurposedStructures/assets/40846040/9f0a0efc-a3f7-4286-953b-4566144c958c)
https://gitlab.com/jeseibel/distant-horizons/-/blob/Data_Source_Rewrite/common/src/main/java/com/seibel/distanthorizons/common/wrappers/worldGeneration/BatchGenerationEnvironment.java#L620

![image](https://github.com/TelepathicGrunt/RepurposedStructures/assets/40846040/ba130c6e-b62c-45e7-8dbc-d9e740e02da0)
![image](https://github.com/TelepathicGrunt/RepurposedStructures/assets/40846040/1573f721-4c00-439b-9ac2-55f8ee533607)
![image](https://github.com/TelepathicGrunt/RepurposedStructures/assets/40846040/316487fe-957f-4849-b3b9-2fcebc20cc66)

**Comment by TelepathicGrunt** [comment]
After talking with Distant Horizon dev and reaching a solution they can do to prevent the side chunks from being in wrong chunkstatus compared to vanilla, I am also removing the logging on my side since the wrongly placed basalt feature issue hasn't happen in a very long time. Should be ok to remove the logging for now.

New update released

**Comment by i493052739** [comment]
Dear author, kindly request for helping to reduce the frequency of this log
lasting for 10min which players walk around at the basalt delta biome, and this log has been printed more than 400 MB

I know it's an issue from another mod and has already located the mod name, but this log is still too freq to print out
the target mod: https://github.com/Scouter456/Nether_Depths_Upgrade 1.18.2 the lastest commit from 3 month ago
