### ISSUE TITLE
IncompatibleClassChangeError with SkullBlock on worldgen

### ISSUE THREAD

**Issue by BlossomZZ** [TelepathicGrunt/RepurposedStructures#332]
[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures/files/15179681/latest.log)
was told to report

**Comment by TelepathicGrunt** [comment]
The title was not right. The crash here is specifically in worldgen. Not entity ticking. And more so, crashing within SkullBlock class when placing it during worldgen.

My mod does not modify the SkullBlock class in any way. You seem to have another mod on that is trying to call a skullblock method but the params are not actually the same at runtime. You would need to remove mods until you find who is causing the crash

**Comment by TelepathicGrunt** [comment]
To help, it seems the method that is crashing is when the SkullBlock is trying to be waterlogged. So that might help narrow down possible mods that could be trying to do waterlogged stuff. You likely may get the crash trying to right click a skullblock with a bucket of water as well
![image](https://github.com/TelepathicGrunt/RepurposedStructures/assets/40846040/7f0b84e7-2163-4684-aecd-ef587a02b4d2)

**Comment by TelepathicGrunt** [comment]
Amendments is the cause
https://github.com/MehVahdJukaar/amendments/issues/72
