### ISSUE TITLE
Inquiry about translations 

### ISSUE THREAD

**Issue by solarsonata** [TelepathicGrunt/RepurposedStructures#334]
I'm working on a mod that adds a structure and biome-locating compass to the nether, and I'm currently adding compatibility with some popular structure mods. As this includes structure name translations for the languages we've currently translated the mod into (German, French and Spanish) I was looking at the RS lang files and I noticed that English has translation keys for all the structures (which follow the format of the auto-detected translation keys that we test if there's no manual one, thank you for that :D).

However, none of the other languages have them (I assume that the structure keys were created after the translations were done?) and while I was originally just going to put manual translations for RS nether structures in my mod and leave it there, I'll have a lot of free time in June and I think I want to try translating all of them into German, French, and Spanish - would you be interested? I'm not a native speaker, instead I have varying levels of school experience in these languages, but since a lot of the RS names are 'vanilla structure + adjective' I think I can do it!

**Comment by TelepathicGrunt** [comment]
Yeah you can provide translations for me. The reason I have the English translations as the keys is because Repurposed Structures is a server side mod that can allow vanilla clients to connect. Since clients without my mod has no lang file with my translations and since explorer maps don’t have a fallback translation atm, they would see the translation keys for the map names. So I use English translations as keys so they see English by default

**Comment by solarsonata** [comment]
I see, that makes sense! I'll start doing the translations in June and make a PR for it :)
