### ISSUE TITLE
Server crash. Failed to create valid structure with all required pieces

### ISSUE THREAD

**Issue by GDudeUnderscore** [TelepathicGrunt/RepurposedStructures#337]
I'm using the Prominence II modpack and when I try to load a chunk with a structure in it this happens:
```
[18:54:53] [Worker-Main-143/ERROR]: 
-------------------------------------------------------------------
Repurposed Structures: Failed to create valid structure with all required pieces starting from this pool file: repurposed_structures:cities/overworld/start_pool. Required pieces failed to generate the required amount are: [repurposed_structures:cities/overworld/fat_tower_top=2]
  This can happen if a structure has a required piece but the structure size is set too low.
  However, this is most likely caused by a structure unable to spawn properly due to hitting the world's min y or max y build thresholds or a broken RS datapack.
  Try teleporting to: class_2338{x=4919, y=67, z=584} and see if the structure generated fine with the required structure piece or if it is indeed missing it.
  Please report the issue to Repurposed Structures's dev with latest.log file if the structure is not cut off by world min/max y build thresholds.
```

As soon as this message appears, the server freezes for a minute and then it crashes,

```
[18:55:20] [spark-async-sampler-worker-thread/WARN]: Timed out waiting for world statistics
[18:55:21] [Server Watchdog/ERROR]: A single server tick took 60.00 seconds (should be max 0.05)
[18:55:21] [Server Watchdog/ERROR]: Considering it to be crashed, server will forcibly shutdown.
[18:55:22] [Server Watchdog/WARN]: Suppressing EXPERIMENTAL level lifecycle
[18:55:22] [Server Watchdog/ERROR]: This crash report has been saved to: /home/********/./crash-reports/crash-2024-05-15_18.55.22-server.txt
```

Here's my [latest.log](https://mclo.gs/ebxeA0b).

**Comment by TelepathicGrunt** [comment]
The message about the city is unrelated to your server deadlocking. The message shows when the generation gave up after trying several times to find a structure layout with all the required pieces. So that generation code is done and no longer running anymore once the message is printed. 

Your deadlock is likely something else. What is strange is the deadlock did not print a thread dump. Can you please put on ModernFix and FullStack Watchdog and try to reproduce the issue. And then share latest.log and the crashlog files from the server? If that still doesn’t have the thread dump, give me the world file itself and coordinate for where issue is and I’ll do a VisualVM thread dump to see exactly what code is locking up the server

**Comment by GDudeUnderscore** [comment]
I'm not sure what happened, but when I added FullStack Watchdog and I went to the coordinates to reproduce the issue, the structure actually generated and the server didn't crash. The server already had ModernFix, if you needed to know. Here's the [world file](https://www.mediafire.com/file/pxnagepmt2mnrfq/archive-2024-05-17T202450Z.tar.gz/file) (it's quite large) and the [latest.log](https://mclo.gs/5vQTo7Y) when it didn't crash.

**Comment by TelepathicGrunt** [comment]
If the crash is no longer reproducible, then I am afraid there is no way we can find what the cause is. Lmk if you encounter it again and what coordinate. But if going to my structure didn't crash, then it is not likely to be my mod since worldgen will (should) generate the same every time for structures since it is seed based.

**Comment by GDudeUnderscore** [comment]
Okay, sorry if I wasted your time or anything like that. I don't know why its crashing but so far I haven't seen it crash again.
