### ISSUE TITLE
1.19.2 Soft-Lock when loading Underground Bastions

### ISSUE THREAD

**Issue by tatoyoda600** [TelepathicGrunt/RepurposedStructures#340]
Was checking out this mod's structures by `/locate`ing them around a world, and everything froze when I tried to teleport to an Underground Bastion. Culled the modpack I was playing down to just 4 mods with which I can reproduce the error, all of which seem to play a part in causing the issue.

Presumably a similar case to #277, but I don't really know how to figure out the cause of the issue to be sure, only that this mod's structure seems to be what starts it.

Was able to narrow it down to the following mod combination:
- [forge-1.19.2-43.4.0-installer.jar](https://files.minecraftforge.net/net/minecraftforge/forge/index_1.19.2.html)
- [blueprint-1.19.2-6.2.0.jar](https://modrinth.com/mod/blueprint/version/6.2.0)
- [environmental-1.19.2-3.1.1.jar](https://modrinth.com/mod/environmental/version/3.1.1)
- [repurposed_structures_forge-6.3.28+1.19.2.jar](https://modrinth.com/mod/repurposed-structures-forge/version/6.3.28+1.19.2)
- [tectonic-forge-1.19-2.3.5a.jar](https://modrinth.com/datapack/tectonic/version/IzZfgym7)
- (No additional datapacks, resource packs, or anything)

Steps I used to consistently repeat the issue:
1. Seed: `-7123539784518700980`
2. Locate Underground Bastion: `/locate structure #repurposed_structures:explorer_maps/bastion_underground`
3. TP to Underground Bastion: `/tp @s 2384 ~ -3888`

No crash report cause it never reaches the crash.
Game log looks fine, it freezes without ever logging anything useful, so the last thing in all my logs is always the result of the `/locate` command, followed by the logs for force quitting Minecraft when I decide to use Task Manager on it:
```
[net.minecraft.server.MinecraftServer/]: tatoyoda600 joined the game
[net.minecraft.advancements.AdvancementList/]: Loaded 19 advancements
[net.minecraft.client.gui.components.ChatComponent/]: [System] [CHAT] The nearest #repurposed_structures:explorer_maps/bastion_underground (repurposed_structures:bastion_underground) is at [2384, ~, -3888] (3696 blocks away)
[net.minecraft.client.Minecraft/]: Stopping!
```
The launcher just tells me that the game was closed forcefully:
```
Process crashed with exit code 1
```

**Comment by TelepathicGrunt** [comment]
This is an Environmental issue caused by this line in their mixin
https://github.com/team-abnormals/environmental/blob/464409ecbfc7668b4703bdfe50e557bfbaf61c80/src/main/java/com/teamabnormals/environmental/core/mixin/MobMixin.java#L46

It is deadlocking the game when a skeleton is spawned by my structure during worldgen. Likely reproducable with a vanilla structure datapack if it contains skeletons saved in structure nbt files.

Environmental would need to fix their mixin. 

I did a thread dump with VisualVM to detect the issue of why the game is stuck
![image](https://github.com/TelepathicGrunt/RepurposedStructures/assets/40846040/de24d4e9-4fac-45f1-aaf1-7912dd4e613e)

There isn't anything I can do here about Environmentals mixin

**Comment by tatoyoda600** [comment]
Ah ok, thanks for the help. Hopefully they'll be willing to fix it.
