### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by gekkone** [TelepathicGrunt/RepurposedStructures#47]
Does the mod support localization? I added the file with the translation to assets (ru_ru.json), but the values from en_us.json are still loaded

**Comment by TelepathicGrunt** [comment]
I'm assuming you are talking about the advancements right? Like I mention at the bottom of my curseforge page, you need the `Translation Advancement pack`. Right now, the advancements do not use translations by default and has the text built into them so that server owners do not need vanilla clients to download a translation resourcepack. To change this, download this datapack and put it into your world so that advancements now do use translations and will use your language file. 
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/releases/download/0.0.8/Repurposed_Structures-Translation_Advancements.zip

Lmk if this doesn't work!
