### ISSUE TITLE
Terraforged compatibility

### ISSUE THREAD

**Issue by FrannDzs** [TelepathicGrunt/RepurposedStructures#53]
Repurposed Structures v2.3.4 (1.16.3 & 1.16.4 & 1.16.5 MC)
Minecraft 1.16.5
Forge 36.0.21
TerraForged 0.2.5

Hello! how are you? I hope it's ok. We have a compatibility issue with TerraForged. I am getting this error on the Minecraft server. This compatibility problem would be solved by adding separation settings.

[21:08:35] [main/WARN] [TerraForged/]: Structure repurposed_structures:village_giant_taiga has been added to 2 biomes but has no separation settings registered for it! We may not be able to generate/locate it :[

**Comment by TelepathicGrunt** [comment]
Closing as it is basically this which you had saw. https://github.com/TelepathicGrunt/RepurposedStructures/issues/52
I am trying to work towards a solution that allows Terraforged to work with other structure mods instead of taking their suggestion of making repurposed structures no longer have dimension blacklisting and incompatible with datapacks/mods using json noise setting files.

It is a frustrating situation as there's nothing I can do on my end without causing my mod to break for other mods/datapacks as well when there's a single line change on their end that they can do.
