### ISSUE TITLE
Unable to localize via resourcepack

### ISSUE THREAD

**Issue by ChromaPIE** [TelepathicGrunt/RepurposedStructures#58]
As has been described from the title, Repurposed Structures seems unable to load (or show) localized texts in the resourcepack. Tested with a self-made resourcepack containing a zh_cn.json (Simplified Chinese) and I'm sure that it's a valid JSON file and has been put under a correct directory. but after several reboots and reloads the localization still couldn't take any effect. By the way it worths a notice that my JSON has been formatted.

**Comment by TelepathicGrunt** [comment]
This is about the advancements correct? Did you put on this resourcepack as well?
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/releases/tag/0.0.8

Basically, repurposed structures ships with advancements already containing english text so that people on servers do not need clients to require a resource pack for translations. But with the resourcepack above, this will force the advancments to now use translation keys and thus, your zh_cn.json file will take effect. 

If you're alright with sharing the zh_cn.json file, may I see it as well? I could also package it with the Translation Advancement pack as well that is on my mod's curseforge page 
![image](https://user-images.githubusercontent.com/40846040/108626173-da947200-741c-11eb-98ff-e3b1624a330e.png)

**Comment by ChromaPIE** [comment]
[zh_cn.zip](https://github.com/TelepathicGrunt/RepurposedStructures/files/6017921/zh_cn.zip)

JSON is not supported for attachment so I zipped it. Seriously translated it even it's intended for personal usage, and I'll be appreciated if it's officially packed.

**Comment by ChromaPIE** [comment]
ALSO PLEASE NOTICE that in quite a lot of the JSONs in the RSTA datapack, the objects after which the localization keys of the titles and description texts were defined, were wrongly named "text", making the game showing bare keys. Editting it to "translate" fixed the problem, and this should be fixed officially too.

**Comment by TelepathicGrunt** [comment]
Oh crap. The new structure's had "text" instead of "translate". nice catch lol. 
And thank you so much! I'll update that datapack to have your translations and fix the other json files

**Comment by ChromaPIE** [comment]
ALLLSO LOL, caught another bug, a duplicated advancement
![image](https://user-images.githubusercontent.com/56111366/108630106-26d3c680-749e-11eb-97f7-bdad196314dc.png)
![image](https://user-images.githubusercontent.com/56111366/108630108-29362080-749e-11eb-8738-f16214536dd0.png)

**Comment by TelepathicGrunt** [comment]
you're on a rolls lol. datapack is now updated with all those fixes
