### ISSUE TITLE
Suggestion/feature

### ISSUE THREAD

**Issue by ShootToKillSTK** [TelepathicGrunt/RepurposedStructures#65]
Would be really cool to be able to edit what kind of mob spawners are used in various structures/dungeons!

Personally not a big fan of most nether ones being zombie pigman which of course are neutral, yet they spawn so often as that type it seems. - Maybe let them spawn as automatically angry? This could make things much harder/balanced!

**Comment by TelepathicGrunt** [comment]
You can actually do that already lol. For code based structures such as dungeons, mineshafts, strongholds, you can edit and use this datapack.
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/releases/tag/0.0.5

For structures that are nbt files, you can go into this world, find the piece, change the mob spawner, and click save on the structure block. Then in the world's save folder for this pieces world, there will be a folder called generated. Take the repurposed_structures folder from that and shove it into the datapack about (so that the two repurposed_structures folders merge together). Now the edited nbt piece will spawn in the world!
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/releases/tag/0.0.10

**Comment by ShootToKillSTK** [comment]
Oh nice, sorry I'm not very familiar with datapacking, is there a way for this to be added automatically to new worlds? For modpacking, assuming simply putting it into the defaultconfigs folder won't work I think ;o

**Comment by TelepathicGrunt** [comment]
Typically, datapacks cannot be global but someone made this mod that forces it to be. I don't know how the mod works but if you can get it up and running, you can use datapacks to customize a ton of other mods as well and package it with the modpack https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack

**Comment by ShootToKillSTK** [comment]
Ah nice! thankss :)
