### ISSUE TITLE
On reload world - Render thread/ERRORs "Not a json array"

### ISSUE THREAD

**Issue by CyberNewty** [TelepathicGrunt/RepurposedStructures#69]
Format of errors:

****************** Blame Report 1.9.2 ******************

 Failed to load resource file: resource_location_here.json

 Reason stated: Not a json array

 Possibly helpful hint (hopefully): 
     This error typically means you need an certain kind of JSON array surrounding
     the current JSON. This is typically seen with worldgen JSON. If this is a worldgen JSON file, then
     check out slicedlime's example datapack for worldgen to find what's off: https://t.co/cm3pJcAHcy?amp=1

 Prettified form of the broken JSON: 
{
  "processor_type": "",
  "modid": "",
  "processor": {
    "processor_type": "rule"
  },
  "forge:registry_name": "resource_name"
}

**Comment by TelepathicGrunt** [comment]
Can you explain a bit more of what's going on? Do you mean you exit a world and then re-enter? How does this relate to Repurposed Structures? Is there any actual effect going on with world generation? What other mods do you have on?

I can't really do much with basically no info.

**Comment by TelepathicGrunt** [comment]
Just tested now with Repurposed Structures and Blame on. I made a world, exit, re-entered, used /reload command, did F3+T to reload resource packs. Nothing. That error did not appear in the logs. This seems more like an issue relating to a different mod and not Repurposed Structures

**Comment by CyberNewty** [comment]
It seems to be centered around a single block from "Outer_end", "azure_wood".

**Comment by CyberNewty** [comment]
Error happens when trying to input into a structure's resource location json.

{
"processor_type":"outer_end:if_loaded",
"modid":"quark",
"processor":
{"processor_type":"rule"},
"forge:registry_name":"outer_end:azure_wood"
}

**Comment by TelepathicGrunt** [comment]
Ah yeah that. I saw that in someone else’s log too and I went to check it out. Turns out, outer end just needed some help with their processor so I made a PR to then here to fix it. https://github.com/BlueDuckYT/The-Outer-End/pull/21

Keep watch on outer end’s next update which should fix their processor. But I’m not sure if it actually is causing any issues right now but better safe than sorry.

I’ll close the report now as this isn’t really related to repurposed structures but thank you for reporting tho!
