### ISSUE TITLE
 MoreVanillaWeapons crashes RS's Temples when mobs gets struck by a dispenser's arrow

### ISSUE THREAD

**Issue by Roritamashi** [TelepathicGrunt/RepurposedStructures#73]
[crash-2021-03-30_19.38.53-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures/files/6233262/crash-2021-03-30_19.38.53-server.txt)
net.minecraft.entity.projectile.ArrowEntity cannot be cast to net.minecraft.entity.LivingEntity

I realized that this happens with the arrows that are launched with the dispensers, I do not know if this is because of the mod but as in the structures there are the arrows with effects, when the dispensers are activated by the mobs the game crashes

**Comment by TelepathicGrunt** [comment]
It looks like the crash is caused whatever mod is calling this method. Do you know what mod is mvw is or which mod's author is mrbelieve?
`com.mrbelieve.mvw.events.ModClientEvents.onVanillaNonCriticalHit1(ModClientEvents.java:122`

The crash is caused by them hooking onto a forge event that triggers when any entity gets hurt. So when the zombified piglin or other mob trigger the temple trap and gets hit by an arrow, that mod runs their code and then crashes because they forgot that entities can be damaged by non-living entities too. This crash should be reproducible by shooting some mobs with arrows from Dispensers even without my mod on

**Comment by TelepathicGrunt** [comment]
Ah got it. It's MoreVanillaWeapons mod. I'll open a bug report to them

**Comment by Roritamashi** [comment]
that was pretty fast thanks for your attention <3
do I need to uninstall the mod from mvw or can I do something to avoid that error

**Comment by TelepathicGrunt** [comment]
There's nothing you can really do to stop their crash as any mob getting struck by non-living entities will crash. I suspect even Ghast's fireballs hitting another mob will also crash the game as well. It's best to remove MVW until they can fix the crash. Here's an issue report I made to them about the issue that you can keep an eye on to know when it is fixed. 
https://www.curseforge.com/minecraft/mc-mods/morevanillaweapons/issues/2

Hopefully they can patch this quickly!

**Comment by TelepathicGrunt** [comment]
Looks like they released a new update v1.7.1 which fixed the crash!
