### ISSUE TITLE
lack of pillagers at rs_outposts in the overworld

### ISSUE THREAD

**Issue by Torben8** [TelepathicGrunt/RepurposedStructures#76]
I'm playing on the latest forge-version of the mod and there seems to be a lack of pillagers spawning at the outposts of this mod making the loot really easy to get and the bad omen effect even harder to get.
Is there a way this can be changed? I noticed this also in older versions.

I'm also using the datapack to change the structures to fit with the savage and ravage style

**Comment by TelepathicGrunt** [comment]
All the regular repurposed structures overworld outposts has 8 pillagers that they spawn at first generation and then they spawn pillagers over time. However, when using the datapack, it switches to using Savage and Ravage's system to spawn the pillagers.

Make sure you have Savage and Ravage on and their mod is on their latest version. What version of Savage and Ravage do you have on?

**Comment by TelepathicGrunt** [comment]
Using Savage and Ravage v3.1.0 with the datapack seems to be working for me 

![image](https://user-images.githubusercontent.com/40846040/113571084-aeefd480-95e3-11eb-8d9c-68516f177ad8.png)

**Comment by TelepathicGrunt** [comment]
![image](https://user-images.githubusercontent.com/40846040/113571173-db0b5580-95e3-11eb-8aad-9da8f9fda4c5.png)
Uh oh. It seems savage and ravage spawns pillagers without persistence on. So that means their pillagers despawns over time which might be what happened to you if you are using the latest savage and ravage. Though the outpost should've replenish the pillagers over time as any monster spawning in the outpost is changed to pillagers

**Comment by Torben8** [comment]
Yeah the persistenceRequired tag might be the cause here. So if i want to fix this I'll have to change the structure files from savage and ravage to have pillagers with the persistenceRequired tag and this will also affect the outposts of this mod too?

About the replenishing of pillagers. I think the spawning of pillagers in vanilla is a lot faster, but this might be caused by other mods in the modpack. Maybe I can figure that one out myself

**Comment by TelepathicGrunt** [comment]
Yes overriding their nbt files with a datapack to have persistence set to true will work. The respawning of pillagers is the same as vanilla's. The only difference is that my outposts does not flatten the entire land into a massive flat slab because it looks a lot better when I do not do that. However, it does mean the bounds for the sides of the outpost might not fully enclose the land which could lead to sloped area not spawning pillagers. That might be why you dont see as many. However, fixing this is a massive amount of work tho
![image](https://user-images.githubusercontent.com/40846040/113574386-fda06d00-95e9-11eb-9775-93dc4e25402b.png)

**Comment by Torben8** [comment]
I see
I fixed the nbt tag in my datapack, so they no longer despawn, that works for me.
That should be enough to make the loot a bit more protected :D
thank you for your time and help.

**Comment by TelepathicGrunt** [comment]
Soon(tm)...
next update will now have the outpost's plates be much larger vertically which should allow for more pillagers to spawn on hillsides and uneven ground! Seemed like they were spawning quite a bit in testing

**Comment by TelepathicGrunt** [comment]
fixed in v2.7.0 which is now released!
