### ISSUE TITLE
[1.16.5] Implement Save My Stronghold generation for strongholds

### ISSUE THREAD

**Issue by NillerMedDild** [TelepathicGrunt/RepurposedStructures#81]
Hello there!

I would like to suggest that you generate Strongholds later in the worldgen process, so caves and such don't cut into them. There's a mod that does this for vanilla stronholds, https://www.curseforge.com/minecraft/mc-mods/save-my-stronghold, but that doesn't work for your strongholds sadly.

**Comment by TelepathicGrunt** [comment]
Save my stronghold is not needed for repurposed structures because my strongholds already will always replace cave air and air unlike vanilla strongholds. If you are seeing my strongholds be carved, then that most likely means another mod's caves or carver is eating at the stronghold and not even Save My Stronghold would prevent that. Quark's crevices is one that I know will eat at strongholds no matter what because their cave isn't actually a carver like it should be. Instead, it's a feature and it runs in such a way that it is carving after strongholds are made and thus, will always eat them. There's nothing that me or Save My Stronghold can do about those other mod's caves if they are doing it as a feature instead of as a carver like they should be.

If you can show me pictures of the carver stronghold, I might be able to recognize which cave mod it is that is eating the stronghold so you know which mod to disable or ask for a config list of blocks their stuff shouldnt carve.

**Comment by TelepathicGrunt** [comment]
Also to be more clear about how Save My Stronghold works, they dont actually change which generation stage the stronghold is in. They just turn off the vanilla behavior where strongholds cannot replace air/cave air. https://github.com/yungnickyoung/Save-My-Stronghold/blob/1.16/src/main/java/com/yungnickyoung/minecraft/savemystronghold/mixin/StrongholdMixin.java

I did the same for my stronghold too cause it was ugly when the stronghold wasn't fully generated

**Comment by NillerMedDild** [comment]
Thanks for the detailed explaination :)

The culprit is indeed Quark's Crevices,
