### ISSUE TITLE
Entering Stonebrick stronghold doesn't grant Eye Spy advancement

### ISSUE THREAD

**Issue by Ketok4321** [TelepathicGrunt/RepurposedStructures#90]

**Comment by TelepathicGrunt** [comment]
you are correct. It grants my own advancement instead and this was intended. You should be able to override the vanilla advancement with a datapack tho and make it also trigger for my stronghold.

Since the Stonebrick Stronghold is planned for removal from my mod in the future, I won't be overriding the vanilla advancement as it could also conflict with other mods as well
