### ISSUE TITLE
Dungeons can't be located with /locate command

### ISSUE THREAD

**Issue by Brun333rp** [TelepathicGrunt/RepurposedStructures#94]
I remember that previously it was possible to find them through this command, but for some reason this is no longer possible

**Comment by TelepathicGrunt** [comment]
I am confused. It was never possible to locate dungeons with the locate command. The command only finds true structures such as villages or temples. Dungeons, however, are a feature which is why they cannot be found with the command. That's why vanilla dungeons and repurposed structures's dungeons are features and unlocatable with the command because multiple dungeons can exist in one chunk which is not possible as a structure.

Hopefully this helps make sense of how Mojange implemented dungeons!
