### ISSUE TITLE
Warped Outpost Config Swapped

### ISSUE THREAD

**Issue by leyxcx** [TelepathicGrunt/RepurposedStructures#99]
Editing configs and I've noticed that the options for adding warped outposts to modded biomes and setting the spawn rates is swapped around
![oop](https://user-images.githubusercontent.com/67163463/119233610-03dcaf80-bb7e-11eb-80df-f7a5910f5a69.png)

**Comment by leyxcx** [comment]
Okay looking at more of them, It seems all the Nether options are jumbled

**Comment by TelepathicGrunt** [comment]
I'm not sure what you are saying is swapped around? The spawnrates are distance between attempts at spawning the structure. So a distance of 3 means on average, the structure will attempt to se if it can spawn every 3 chunks. If it was 50, then it will check every 50 chunks instead.

So lower numbers means more attempts at spawning while higher numbers means more rarer. It isn't like the spawnrates that mineshafts and dungeons do because most structures operate on spacing between spawn attempts instead.

**Comment by TelepathicGrunt** [comment]
ooooh the comments. I see now my bad. I'll look into it

**Comment by TelepathicGrunt** [comment]
alright I fixed all the outposts config comments. I checked the other configs quickly and didn't see anything else that was wrong but poke me if I missed anything lol. Thank you for reporting this! Will be fixed next update

**Comment by TelepathicGrunt** [comment]
fixed in v2.7.0 which is now released!
